# Generated by Django 5.0.6 on 2024-07-21 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APIPage',
        ),
    ]
