# Generated by Django 5.0.6 on 2024-07-31 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='form_subtitle',
            field=models.CharField(blank=True, max_length=255, verbose_name='Form subtitle'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='form_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Form title'),
        ),
    ]
