# Generated by Django 5.0.6 on 2024-07-31 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactpage_form_subtitle_contactpage_form_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='thank_you_text',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
