# Generated by Django 5.0.6 on 2024-07-31 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contactpage_thank_you_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='thank_you_text',
        ),
    ]
