# Generated by Django 5.0.6 on 2024-08-04 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_remove_contactpage_thank_you_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='intro',
        ),
    ]
