# Generated by Django 5.0.6 on 2024-08-04 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_remove_contactpage_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='form_subtitle',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='form_title',
        ),
    ]
