# Generated by Django 5.0.6 on 2024-08-06 17:22

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_remove_contactpage_form_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactfield',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_form_fields', to='contact.contactpage'),
        ),
    ]
