# Generated by Django 5.0.2 on 2024-05-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbif', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxon',
            name='id',
        ),
        migrations.AddField(
            model_name='taxon',
            name='taxon_id',
            field=models.BigIntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
