# Generated by Django 5.0.6 on 2024-07-29 20:28

import django.db.models.deletion
import inventorytags.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NearFieldCommunicationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('serial_number', models.CharField(db_index=True, editable=False, max_length=32, unique=True, validators=[inventorytags.validators.validate_serial_number])),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'near field communication tag',
                'verbose_name_plural': 'near field communication tags',
            },
        ),
        migrations.CreateModel(
            name='InventoryLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('link', models.URLField(blank=True, max_length=255, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='inventorytags.nearfieldcommunicationtag')),
            ],
            options={
                'verbose_name': 'inventory link',
                'verbose_name_plural': 'inventory links',
                'indexes': [models.Index(fields=['content_type'], name='inventoryta_content_049509_idx'), models.Index(fields=['object_id'], name='inventoryta_object__9f38cf_idx'), models.Index(fields=['tag'], name='inventoryta_tag_id_c71626_idx')],
            },
        ),
    ]
