# Generated by Django 5.0.6 on 2024-07-21 02:18

import django.db.models.deletion
import inventorytags.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NearFieldCommunicationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('serial_number', models.CharField(db_index=True, editable=False, max_length=32, unique=True, validators=[inventorytags.validators.validate_serial_number])),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'near field communication tag',
                'verbose_name_plural': 'near field communication tags',
            },
        ),
        migrations.CreateModel(
            name='InventoryLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.inventorypage')),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='inventorytags.nearfieldcommunicationtag')),
            ],
            options={
                'verbose_name': 'inventory link',
                'verbose_name_plural': 'inventory links',
                'indexes': [models.Index(fields=['inventory'], name='inventoryta_invento_d1d080_idx'), models.Index(fields=['tag'], name='inventoryta_tag_id_c71626_idx')],
                'unique_together': {('inventory', 'tag')},
            },
        ),
    ]
