# Generated by Django 5.0.6 on 2024-08-04 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventorytags', '0003_alter_inventorylink_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorylink',
            old_name='link',
            new_name='url',
        ),
    ]
