# Generated by Django 5.0.2 on 2024-04-02 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productindexpage',
            name='heading_intro',
        ),
        migrations.RemoveField(
            model_name='productindexpage',
            name='heading_title',
        ),
        migrations.RemoveField(
            model_name='productpage',
            name='heading_intro',
        ),
        migrations.RemoveField(
            model_name='productpage',
            name='heading_title',
        ),
    ]
