PREDEFINED_CSS_STYLES=[
    ('heading-hero', 'Hero'),
    ('heading', 'Default'),
    ('heading.large', 'Large'),
    ('heading.banner', 'Banner'),
    ('heading-contact-lottie', 'Contact Lottie'),
    ('heading-accordion', 'Accordion'),
    ('heading-top', 'Top'),
    ('heading-solution-large', 'Solution Large'),
    ('heading-solution-large green', 'Solution Large Green'),
    ('heading-list.blue', 'List Blue'),
    ('heading-list.green', 'List Green'),
    ('heading-about', 'About'),
    ('heading-about green', 'About Green'),
    ('heading-about red', 'About Red'),
    ('heading-name', 'Name'),
    ('heading-account', 'Account'),
    ('heading-account white', 'Account White'),
    ('heading-template', 'Template'),
]