# Generated by Django 4.2.6 on 2024-01-11 02:15

import apps.utils.custom_storage
import apps.utils.helpers.get_path
import apps.utils.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirmed', models.BooleanField(default=False, help_text='Indicates whether the user has confirmed their email address.')),
                ('bio', models.TextField(blank=True, help_text='A short biography of the user.', max_length=500)),
                ('location', models.CharField(blank=True, help_text='The location of the user.', max_length=30)),
                ('birth_date', models.DateField(blank=True, help_text='The birth date of the user.', null=True)),
                ('avatar', models.ImageField(blank=True, help_text='The profile picture of the user.', null=True, storage=apps.utils.custom_storage.PublicMediaStorage(), upload_to=apps.utils.helpers.get_path.get_unique_filename, validators=[apps.utils.validators.validate_image_size_and_dimensions])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the profile was created.', verbose_name='Created At')),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='The date and time when the profile was last modified.', verbose_name='Last Modified')),
                ('user', models.OneToOneField(help_text='The user associated with this profile.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('plant', 'Plant')], help_text='Type of the item involved in the activity, such as "plant" or "cea".', max_length=25)),
                ('activity_status', models.CharField(choices=[('register', 'Registered'), ('update', 'Updated'), ('delete', 'Deleted')], help_text='Nature of the activity (e.g., "created", "updated", "deleted").', max_length=20)),
                ('content', models.TextField(help_text='Detailed description of the activity.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='The date and time when the activity was recorded.')),
                ('user', models.ForeignKey(help_text='Reference to the user who performed the activity.', on_delete=django.db.models.deletion.CASCADE, related_name='recent_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
