# Generated by Django 4.1.7 on 2023-06-25 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_avatar_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='accounts_profile'
        ),
    ]
