# Generated by Django 4.1.7 on 2023-06-26 23:40

import apps.utils.custom_storage
import apps.utils.helpers
import apps.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230625_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='The profile picture of the user.', null=True, upload_to=apps.utils.custom_storage.AvatarStorage(apps.utils.helpers.get_user_directory_path), validators=[apps.utils.validators.validate_image_size_and_dimensions]),
        ),
        migrations.AlterModelTable(
            name='profile',
            table=None,
        ),
    ]
