# Generated by Django 4.1.7 on 2023-06-27 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_alter_profile_avatar_alter_profile_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_status', models.CharField(choices=[('register', 'Registered'), ('update', 'Updated'), ('delete', 'Deleted')], max_length=20)),
                ('activity_type', models.CharField(choices=[('plant', 'Plant'), ('label grouping', 'Label Grouping'), ('greenhouse', 'Greenhouse'), ('growth chamber', 'Growth Chamber'), ('tissue culture chamber', 'Tissue Culture Chamber')], max_length=25)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
