# Generated by Django 4.1.7 on 2023-07-22 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_experience_profile_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('plant', 'Plant'), ('growing_fertilizer', 'Growing Fertilizer'), ('growing_label', 'Growing Label'), ('growing_medium', 'Growing Medium'), ('growing_component', 'Growing Component'), ('greenhouse', 'Greenhouse'), ('growth chamber', 'Growth Chamber'), ('tissue culture chamber', 'Tissue Culture Chamber')], max_length=25),
        ),
    ]
