# Generated by Django 4.2.6 on 2023-11-24 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_profile_experience_remove_profile_interests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('plant', 'Plant'), ('animal', 'Animal')], max_length=25),
        ),
    ]
