# Generated by Django 4.2.6 on 2024-01-08 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0010_alter_profile_options_profile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_confirmed',
            field=models.BooleanField(default=False, help_text='Indicates whether the user has confirmed their email address.'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_status',
            field=models.CharField(choices=[('register', 'Registered'), ('update', 'Updated'), ('delete', 'Deleted')], help_text='Nature of the activity (e.g., "created", "updated", "deleted").', max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('plant', 'Plant'), ('animal', 'Animal')], help_text='Type of the item involved in the activity, such as "plant" or "cea".', max_length=25),
        ),
        migrations.AlterField(
            model_name='activity',
            name='content',
            field=models.TextField(help_text='Detailed description of the activity.'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when the activity was recorded.'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(help_text='Reference to the user who performed the activity.', on_delete=django.db.models.deletion.CASCADE, related_name='recent_activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
