# Generated by Django 4.2.6 on 2024-01-08 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_email_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('plant', 'Plant')], help_text='Type of the item involved in the activity, such as "plant" or "cea".', max_length=25),
        ),
    ]
