# Generated by Django 4.2.9 on 2024-02-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the person submitting the contact form.', max_length=256, verbose_name='Name')),
                ('email', models.EmailField(help_text='The email address of the person submitting the contact form.', max_length=254, verbose_name='Email')),
                ('message', models.TextField(help_text='The message content from the contact form.', verbose_name='Message')),
                ('response_received', models.BooleanField(default=False, help_text='Whether this contact instance has received a response for the message.', verbose_name='Response Received')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the contact form was submitted.', verbose_name='Created At')),
            ],
        ),
    ]
