# Generated by Django 4.2.6 on 2024-01-26 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactModel',
            new_name='Contact',
        ),
    ]
