# Generated by Django 4.2.6 on 2024-02-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_contactmodel_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='response_received',
            field=models.BooleanField(default=False, help_text='Whether this contact instance has received a response for the message.', verbose_name='Response Received'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when the contact form was submitted.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(help_text='The email address of the person submitting the contact form.', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(help_text='The message content from the contact form.', verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(help_text='The name of the person submitting the contact form.', max_length=256, verbose_name='Name'),
        ),
    ]
