# Generated by Django 5.0.2 on 2024-03-24 03:07

import base.fields.django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallToActionBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', base.fields.django.BaseCharField(blank=True, help_text='Subtitle text', max_length=255, null=True)),
                ('heading', base.fields.django.BaseCharField(blank=True, help_text='Main heading text', max_length=255, null=True)),
                ('call_to_action_page', base.fields.django.BaseForeignKey(blank=True, help_text='Page to link the call to action to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
