# Generated by Django 5.0.2 on 2024-03-30 23:16

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersettings',
            name='content',
            field=wagtail.fields.StreamField([('logo', wagtail.images.blocks.ImageChooserBlock(icon='image')), ('paragraph', wagtail.blocks.TextBlock(icon='pilcrow')), ('contact', wagtail.blocks.StructBlock([])), ('link', wagtail.blocks.StructBlock([('category', wagtail.blocks.ChoiceBlock(choices=[('company', 'Company Information'), ('news', 'News & Events'), ('social', 'Social Links')]))], icon='link')), ('copyright', wagtail.blocks.CharBlock(required=False)), ('credits', wagtail.blocks.CharBlock(required=False))], blank=True, null=True),
        ),
    ]
