# Generated by Django 5.0.2 on 2024-03-22 04:15

import base.fields.django_fields
import base.fields.wagtail_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companypagegalleryimage',
            name='page',
        ),
        migrations.RemoveField(
            model_name='companypagegalleryimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='contactfield',
            name='page',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='pricingindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='pricingpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='pricingpage',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='pricingpagetag',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='pricingpagegalleryimage',
            name='page',
        ),
        migrations.RemoveField(
            model_name='pricingpagegalleryimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='pricingpagetag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='pricingtagindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='solutionindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='solutionpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='solutionpage',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='solutionpagegalleryimage',
            name='page',
        ),
        migrations.RemoveField(
            model_name='solutionpagetag',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='solutionpagegalleryimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='solutionpagetag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='solutiontagindexpage',
            name='page_ptr',
        ),
        migrations.AlterField(
            model_name='footernavigationsettings',
            name='github_url',
            field=base.models.django_fields.BaseURLField(blank=True, verbose_name='GitHub URL'),
        ),
        migrations.AlterField(
            model_name='footernavigationsettings',
            name='linkedin_url',
            field=base.models.django_fields.BaseURLField(blank=True, verbose_name='LinkedIn URL'),
        ),
        migrations.AlterField(
            model_name='footernavigationsettings',
            name='twitter_url',
            field=base.models.django_fields.BaseURLField(blank=True, verbose_name='Twitter URL'),
        ),
        migrations.AlterField(
            model_name='footertext',
            name='body',
            field=base.models.wagtail_fields.BaseRichTextField(),
        ),
        migrations.DeleteModel(
            name='CompanyPage',
        ),
        migrations.DeleteModel(
            name='CompanyPageGalleryImage',
        ),
        migrations.DeleteModel(
            name='ContactField',
        ),
        migrations.DeleteModel(
            name='ContactPage',
        ),
        migrations.DeleteModel(
            name='PricingIndexPage',
        ),
        migrations.DeleteModel(
            name='PricingPage',
        ),
        migrations.DeleteModel(
            name='PricingPageGalleryImage',
        ),
        migrations.DeleteModel(
            name='PricingPageTag',
        ),
        migrations.DeleteModel(
            name='PricingTagIndexPage',
        ),
        migrations.DeleteModel(
            name='SolutionIndexPage',
        ),
        migrations.DeleteModel(
            name='SolutionPage',
        ),
        migrations.DeleteModel(
            name='SolutionPageGalleryImage',
        ),
        migrations.DeleteModel(
            name='SolutionPageTag',
        ),
        migrations.DeleteModel(
            name='SolutionTagIndexPage',
        ),
    ]
