# Generated by Django 5.0.2 on 2024-03-22 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='headertext',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='headertext',
            name='latest_revision',
        ),
        migrations.RemoveField(
            model_name='headertext',
            name='live_revision',
        ),
        migrations.RemoveField(
            model_name='headertext',
            name='locale',
        ),
        migrations.DeleteModel(
            name='FooterText',
        ),
        migrations.DeleteModel(
            name='HeaderText',
        ),
    ]
