# Generated by Django 5.0.2 on 2024-06-06 23:33

import django.db.models.deletion
import wagtail.models.collections
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_digideximage_digidexrendition'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digideximage',
            name='user',
        ),
        migrations.AlterField(
            model_name='digideximage',
            name='collection',
            field=models.ForeignKey(default=wagtail.models.collections.get_root_collection_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.collection', verbose_name='collection'),
        ),
    ]
