# Generated by Django 5.0.2 on 2024-03-27 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_basepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footernavigationsettings',
            name='linkedin_url',
        ),
    ]
