# Generated by Django 5.0.2 on 2024-06-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_digideximage_digidexrendition'),
    ]

    operations = [
        migrations.AddField(
            model_name='digideximage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='digideximage',
            name='caption',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
