# Generated by Django 5.0.2 on 2024-04-01 15:35

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_footersettings_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersettings',
            name='content',
            field=wagtail.fields.StreamField([('logo', wagtail.blocks.StructBlock([('logo', wagtail.images.blocks.ImageChooserBlock(required=True)), ('alt_text', wagtail.blocks.CharBlock(required=False)), ('home', wagtail.blocks.PageChooserBlock(required=False))])), ('paragraph', wagtail.blocks.CharBlock()), ('copyright', wagtail.blocks.CharBlock(required=False)), ('credits', wagtail.blocks.CharBlock(required=False))], blank=True, null=True),
        ),
    ]
