# Generated by Django 5.0.6 on 2024-07-23 23:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_digidexlogo_options_digidexfootercopyright_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0093_uploadedfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DigiDexImage',
            new_name='BaseImage',
        ),
        migrations.RenameModel(
            old_name='DigiDexRendition',
            new_name='BaseRendition',
        ),
        migrations.RenameModel(
            old_name='DigiDexFooterCopyright',
            new_name='FooterCopyright',
        ),
        migrations.RenameModel(
            old_name='DigiDexFooterParagraph',
            new_name='FooterParagraph',
        ),
        migrations.RenameModel(
            old_name='DigiDexLogo',
            new_name='SiteLogo',
        ),
        migrations.AlterModelOptions(
            name='footercopyright',
            options={'verbose_name': 'Footer Copyright', 'verbose_name_plural': 'Footer Copyrights'},
        ),
        migrations.AlterModelOptions(
            name='footerparagraph',
            options={'verbose_name': 'Footer Paragraph', 'verbose_name_plural': 'Footer Paragraphs'},
        ),
        migrations.AlterModelOptions(
            name='sitelogo',
            options={'verbose_name': 'Site Logo', 'verbose_name_plural': 'Site Logos'},
        ),
    ]
