# Generated by Django 5.0.6 on 2024-07-31 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_footerbanner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footerbanner',
            old_name='body',
            new_name='title',
        ),
    ]
