# Generated by Django 5.0.2 on 2024-04-01 23:02

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_footersettings_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersettings',
            name='content',
            field=wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock())], blank=True, null=True),
        ),
    ]
