# Generated by Django 5.0.2 on 2024-04-23 06:50

import django.db.models.deletion
import uuid
import wagtail.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_copyrightsnippet_creditsnippet_and_more'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagefooter',
            name='copyright',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pagefooter',
            name='credit',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='pagefooter',
            name='content',
        ),
        migrations.AddField(
            model_name='pagefooter',
            name='paragraph',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='HeaderAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('live', models.BooleanField(default=True, editable=False, verbose_name='live')),
                ('has_unpublished_changes', models.BooleanField(default=False, editable=False, verbose_name='has unpublished changes')),
                ('first_published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='first published at')),
                ('last_published_at', models.DateTimeField(editable=False, null=True, verbose_name='last published at')),
                ('go_live_at', models.DateTimeField(blank=True, null=True, verbose_name='go live date/time')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='expiry date/time')),
                ('expired', models.BooleanField(default=False, editable=False, verbose_name='expired')),
                ('url', models.URLField(blank=True, null=True)),
                ('text', models.TextField(max_length=255)),
                ('latest_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='latest revision')),
                ('live_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='live revision')),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale')),
            ],
            options={
                'verbose_name_plural': 'Advertisements',
                'abstract': False,
                'unique_together': {('translation_key', 'locale')},
            },
            bases=(wagtail.models.PreviewableMixin, models.Model),
        ),
        migrations.DeleteModel(
            name='AdvertisementBanner',
        ),
        migrations.DeleteModel(
            name='CopyrightSnippet',
        ),
        migrations.DeleteModel(
            name='CreditSnippet',
        ),
    ]
