# Generated by Django 5.0.2 on 2024-03-27 20:23

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_delete_basepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', wagtail.fields.StreamField([('logo', wagtail.images.blocks.ImageChooserBlock(icon='image')), ('paragraph', wagtail.blocks.RichTextBlock(icon='pilcrow')), ('contact', wagtail.blocks.StructBlock([])), ('link', wagtail.blocks.StructBlock([('category', wagtail.blocks.ChoiceBlock(choices=[('company', 'Company Information'), ('news', 'News & Events'), ('social', 'Connect With Us')]))], icon='link')), ('copyright', wagtail.blocks.TextBlock(required=False)), ('credits', wagtail.blocks.TextBlock(required=False))], blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Footer Settings',
            },
        ),
        migrations.DeleteModel(
            name='FooterNavigationSettings',
        ),
        migrations.DeleteModel(
            name='FooterText',
        ),
    ]
