# Generated by Django 5.0.6 on 2024-07-24 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_digideximage_baseimage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseimage',
            old_name='alt_text',
            new_name='alt',
        ),
    ]
