# Generated by Django 5.0.2 on 2024-06-24 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_navigationsettings_footercopyright'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub URL')),
                ('signup', models.URLField(verbose_name='Signup URL')),
                ('login', models.URLField(verbose_name='Login URL')),
                ('logout', models.URLField(verbose_name='Logout URL')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='NavigationSettings',
        ),
    ]
