# Generated by Django 5.0.6 on 2024-08-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_body_footerbanner_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationsettings',
            name='chat_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
