# Generated by Django 5.0.2 on 2024-04-25 04:31

import django.db.models.deletion
import uuid
import wagtail.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_pagefooter_copyright_alter_pagefooter_credit_and_more'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HeaderAdvertisement',
            new_name='AdvertBanner',
        ),
        migrations.AlterModelOptions(
            name='advertbanner',
            options={'verbose_name_plural': 'Advert Banners'},
        ),
        migrations.AlterModelOptions(
            name='pagefooter',
            options={'verbose_name': 'Footer', 'verbose_name_plural': 'Footer Settings'},
        ),
        migrations.AlterUniqueTogether(
            name='pagefooter',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='company',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='github',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='solutions',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='twitter',
        ),
        migrations.AddField(
            model_name='pagefooter',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Blog Page'),
        ),
        migrations.AddField(
            model_name='pagefooter',
            name='chat',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Support Chat URL'),
        ),
        migrations.AddField(
            model_name='pagefooter',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Company Page'),
        ),
        migrations.AddField(
            model_name='pagefooter',
            name='credits',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pagefooter',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Support Email Address'),
        ),
        migrations.AddField(
            model_name='pagefooter',
            name='github',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='GitHub URL'),
        ),
        migrations.AddField(
            model_name='pagefooter',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Support Phone Number'),
        ),
        migrations.AddField(
            model_name='pagefooter',
            name='solutions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Solutions Page'),
        ),
        migrations.AddField(
            model_name='pagefooter',
            name='support',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Support Page'),
        ),
        migrations.AddField(
            model_name='pagefooter',
            name='twitter',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Twitter URL'),
        ),
        migrations.AlterField(
            model_name='pagefooter',
            name='copyright',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='pagefooter',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='pagefooter',
            name='expire_at',
        ),
        migrations.RemoveField(
            model_name='pagefooter',
            name='expired',
        ),
        migrations.RemoveField(
            model_name='pagefooter',
            name='first_published_at',
        ),
        migrations.RemoveField(
            model_name='pagefooter',
            name='go_live_at',
        ),
        migrations.RemoveField(
            model_name='pagefooter',
            name='has_unpublished_changes',
        ),
        migrations.RemoveField(
            model_name='pagefooter',
            name='last_published_at',
        ),
        migrations.RemoveField(
            model_name='pagefooter',
            name='latest_revision',
        ),
        migrations.RemoveField(
            model_name='pagefooter',
            name='live',
        ),
        migrations.RemoveField(
            model_name='pagefooter',
            name='live_revision',
        ),
        migrations.RemoveField(
            model_name='pagefooter',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='pagefooter',
            name='paragraph',
        ),
        migrations.RemoveField(
            model_name='pagefooter',
            name='translation_key',
        ),
        migrations.CreateModel(
            name='CallToActionBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('live', models.BooleanField(default=True, editable=False, verbose_name='live')),
                ('has_unpublished_changes', models.BooleanField(default=False, editable=False, verbose_name='has unpublished changes')),
                ('first_published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='first published at')),
                ('last_published_at', models.DateTimeField(editable=False, null=True, verbose_name='last published at')),
                ('go_live_at', models.DateTimeField(blank=True, null=True, verbose_name='go live date/time')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='expiry date/time')),
                ('expired', models.BooleanField(default=False, editable=False, verbose_name='expired')),
                ('url', models.URLField(blank=True, null=True)),
                ('text', models.TextField(max_length=255)),
                ('latest_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='latest revision')),
                ('live_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='live revision')),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale')),
            ],
            options={
                'verbose_name_plural': 'Call To Action Banners',
                'abstract': False,
                'unique_together': {('translation_key', 'locale')},
            },
            bases=(wagtail.models.PreviewableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='NavigationBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('live', models.BooleanField(default=True, editable=False, verbose_name='live')),
                ('has_unpublished_changes', models.BooleanField(default=False, editable=False, verbose_name='has unpublished changes')),
                ('first_published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='first published at')),
                ('last_published_at', models.DateTimeField(editable=False, null=True, verbose_name='last published at')),
                ('go_live_at', models.DateTimeField(blank=True, null=True, verbose_name='go live date/time')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='expiry date/time')),
                ('expired', models.BooleanField(default=False, editable=False, verbose_name='expired')),
                ('url', models.URLField(blank=True, null=True)),
                ('text', models.TextField(max_length=255)),
                ('latest_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='latest revision')),
                ('live_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='live revision')),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale')),
            ],
            options={
                'verbose_name_plural': 'Navigation Bars',
                'abstract': False,
                'unique_together': {('translation_key', 'locale')},
            },
            bases=(wagtail.models.PreviewableMixin, models.Model),
        ),
    ]
