# Generated by Django 5.0.2 on 2024-04-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_notificationbarsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter URL')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub URL')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='NotificationBarSettings',
        ),
    ]
