# Generated by Django 5.0.6 on 2024-08-01 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_navigationsettings_chat_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationsettings',
            name='logo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.baseimage'),
        ),
    ]
