# Generated by Django 5.0.2 on 2024-04-02 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_navigationsettings_delete_notificationbarsettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NavigationSettings',
            new_name='SocialMediaSettings',
        ),
        migrations.DeleteModel(
            name='FooterSettings',
        ),
    ]
