# Generated by Django 5.0.6 on 2024-08-01 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_navigationsettings_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationsettings',
            name='chat_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='navigationsettings',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='navigationsettings',
            name='github_url',
            field=models.URLField(blank=True, null=True, verbose_name='GitHub URL'),
        ),
        migrations.AlterField(
            model_name='navigationsettings',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.baseimage'),
        ),
        migrations.AlterField(
            model_name='navigationsettings',
            name='mastodon_url',
            field=models.URLField(blank=True, null=True, verbose_name='Mastodon URL'),
        ),
        migrations.AlterField(
            model_name='navigationsettings',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='navigationsettings',
            name='twitter_url',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter URL'),
        ),
    ]
