# Generated by Django 5.0.2 on 2024-04-25 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_footercopyright_footerinformation_footersociallinks_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footerinformation',
            options={},
        ),
    ]
