# Generated by Django 5.0.6 on 2024-08-03 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_navigationsettings_chat_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseimage',
            name='caption',
        ),
    ]
