# Generated by Django 5.0.2 on 2024-04-25 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_footerinformation_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterCopyright',
        ),
    ]
