# Generated by Django 5.0.2 on 2024-04-02 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_footertext'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, help_text='Support Email Address', max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Support Phone Number', max_length=255, null=True)),
                ('chat', models.URLField(blank=True, help_text='URL to launch Support Chat', null=True)),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter URL')),
                ('github', models.URLField(blank=True, verbose_name='GitHub URL')),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('solutions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='aboutussettings',
            name='company',
        ),
        migrations.RemoveField(
            model_name='aboutussettings',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='newsandeventssettings',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='newsandeventssettings',
            name='solutions',
        ),
        migrations.DeleteModel(
            name='SocialMediaSettings',
        ),
        migrations.DeleteModel(
            name='AboutUsSettings',
        ),
        migrations.DeleteModel(
            name='NewsAndEventsSettings',
        ),
    ]
