# Generated by Django 5.0.2 on 2024-04-02 17:13

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_navigationsettings_remove_aboutussettings_company_and_more'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footertext',
            options={'verbose_name_plural': 'Footer Configurations'},
        ),
        migrations.AddField(
            model_name='footertext',
            name='copyright',
            field=wagtail.fields.RichTextField(blank=True, help_text='Copyright notice for the footer.'),
        ),
        migrations.AddField(
            model_name='footertext',
            name='credits',
            field=wagtail.fields.RichTextField(blank=True, help_text='Site credits or acknowledgments for the footer.'),
        ),
        migrations.AddField(
            model_name='footertext',
            name='logo',
            field=models.ForeignKey(blank=True, help_text='Logo to display in the footer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='footertext',
            name='body',
            field=wagtail.fields.RichTextField(help_text='Main content for the footer.'),
        ),
    ]
