# Generated by Django 5.0.2 on 2024-04-02 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_footercontent_footernotice_delete_footertext'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footercontent',
            options={'verbose_name_plural': 'Footer Contents'},
        ),
    ]
