# Generated by Django 5.0.2 on 2024-04-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_footercopyright'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticatedNavbarButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='Link URL')),
                ('text', models.CharField(max_length=255, verbose_name='Button Text')),
                ('fill', models.CharField(help_text='Outline or Solid', max_length=255, verbose_name='Button Fill')),
            ],
            options={
                'verbose_name': 'Authenticated Navbar Button',
                'verbose_name_plural': 'Authenticated Navbar Buttons',
            },
        ),
        migrations.CreateModel(
            name='NonAuthenticatedNavbarButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='Link URL')),
                ('text', models.CharField(max_length=255, verbose_name='Button Text')),
                ('fill', models.CharField(help_text='Outline or Solid', max_length=255, verbose_name='Button Fill')),
            ],
            options={
                'verbose_name': 'Non-Authenticated Navbar Button',
                'verbose_name_plural': 'Non-Authenticated Navbar Buttons',
            },
        ),
    ]
