# Generated by Django 5.0.2 on 2024-04-26 22:12

import django.db.models.deletion
import wagtail.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_authenticatednavbarbutton_and_more'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live', models.BooleanField(default=True, editable=False, verbose_name='live')),
                ('has_unpublished_changes', models.BooleanField(default=False, editable=False, verbose_name='has unpublished changes')),
                ('first_published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='first published at')),
                ('last_published_at', models.DateTimeField(editable=False, null=True, verbose_name='last published at')),
                ('go_live_at', models.DateTimeField(blank=True, null=True, verbose_name='go live date/time')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='expiry date/time')),
                ('expired', models.BooleanField(default=False, editable=False, verbose_name='expired')),
                ('paragraph', models.TextField(blank=True, max_length=255, null=True)),
                ('latest_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='latest revision')),
                ('live_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='live revision')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.models.PreviewableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='NavigationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github', models.URLField(blank=True, max_length=255, null=True, verbose_name='GitHub URL')),
                ('twitter', models.URLField(blank=True, max_length=255, null=True, verbose_name='Twitter URL')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email Address')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone Number')),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Blog Page')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Company Page')),
                ('login', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Login User Page')),
                ('logo', models.ForeignKey(blank=True, help_text='Company Logo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('logout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Logout User Page')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='User Profile Page')),
                ('signup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Signup User Page')),
                ('solutions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Solutions Page')),
                ('support', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Support Page')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='AuthenticatedNavbarButton',
        ),
        migrations.RemoveField(
            model_name='footerinformation',
            name='latest_revision',
        ),
        migrations.RemoveField(
            model_name='footerinformation',
            name='live_revision',
        ),
        migrations.RemoveField(
            model_name='footerinternallinks',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='footerinternallinks',
            name='company',
        ),
        migrations.RemoveField(
            model_name='footerinternallinks',
            name='latest_revision',
        ),
        migrations.RemoveField(
            model_name='footerinternallinks',
            name='live_revision',
        ),
        migrations.RemoveField(
            model_name='footerinternallinks',
            name='solutions',
        ),
        migrations.RemoveField(
            model_name='footerinternallinks',
            name='support',
        ),
        migrations.RemoveField(
            model_name='footersociallinks',
            name='latest_revision',
        ),
        migrations.RemoveField(
            model_name='footersociallinks',
            name='live_revision',
        ),
        migrations.DeleteModel(
            name='NonAuthenticatedNavbarButton',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='logo',
        ),
        migrations.DeleteModel(
            name='FooterInformation',
        ),
        migrations.DeleteModel(
            name='FooterInternalLinks',
        ),
        migrations.DeleteModel(
            name='FooterSocialLinks',
        ),
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
