# Generated by Django 5.0.2 on 2024-04-27 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_footerparagraph_navigationsettings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationsettings',
            name='login',
        ),
        migrations.RemoveField(
            model_name='navigationsettings',
            name='logout',
        ),
        migrations.RemoveField(
            model_name='navigationsettings',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='navigationsettings',
            name='signup',
        ),
    ]
