# Generated by Django 5.0.2 on 2024-04-27 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_navigationsettings_login_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footercopyright',
            old_name='text',
            new_name='copyright',
        ),
    ]
