# Generated by Django 5.0.2 on 2024-05-23 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_rename_text_footercopyright_copyright'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footerparagraph',
            name='latest_revision',
        ),
        migrations.RemoveField(
            model_name='footerparagraph',
            name='live_revision',
        ),
        migrations.DeleteModel(
            name='FooterCopyright',
        ),
        migrations.DeleteModel(
            name='FooterParagraph',
        ),
    ]
