# Generated by Django 5.0.2 on 2024-04-02 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0004_alter_solutionsindexpage_features_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solutionsindexpage',
            name='features',
        ),
        migrations.RemoveField(
            model_name='solutionsindexpage',
            name='solutions',
        ),
        migrations.DeleteModel(
            name='SolutionsPage',
        ),
    ]
