# Generated by Django 5.0.2 on 2024-04-02 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0005_remove_solutionsindexpage_features_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solutionsindexpage',
            name='heading_intro',
        ),
        migrations.RemoveField(
            model_name='solutionsindexpage',
            name='heading_title',
        ),
    ]
