# Generated by Django 4.2.6 on 2024-01-11 20:58

import digit.utils.custom_storage
import digit.utils.validators
from digit.journal.models import journal_entry_directory_path
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this journal entry was created.', verbose_name='Created At')),
                ('content', models.TextField(help_text='The textual content of the journal entry.', verbose_name='Content')),
                ('image', models.ImageField(blank=True, help_text='(Optional) The image to save with the journal entry. Only .jpg, .png, and .jpeg extensions are allowed.', null=True, storage=digit.utils.custom_storage.PrivateMediaStorage(), upload_to=journal_entry_directory_path, validators=[digit.utils.validators.validate_journal_entry])),
                ('watered', models.BooleanField(default=False, help_text='Indicates whether the digitized plant was watered in this journal entry.', verbose_name='Watered')),
                ('fertilized', models.BooleanField(default=False, help_text='Indicates whether the digitized plant was fertilized in this journal entry.', verbose_name='Fertilized')),
                ('cleaned', models.BooleanField(default=False, help_text='Indicates whether the digitized plant was cleaned in this journal entry.', verbose_name='Cleaned')),
                ('digit', models.ForeignKey(help_text='The digitized plant to which this journal entry is related.', on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='inventory.digit')),
                ('user', models.ForeignKey(help_text='The user who created this journal entry.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
