# Generated by Django 4.2.6 on 2024-01-22 04:36

import digit.journal.models.entry
import digit.utils.custom_storage
import digit.utils.validators.journal_entry_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_alter_entry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=models.ImageField(blank=True, help_text='(Optional) The image to save with the journal entry. Only .jpg, .png, and .jpeg extensions are allowed.', null=True, storage=digit.utils.custom_storage.PrivateMediaStorage(), upload_to=journal.models.entry.journal_entry_directory_path, validators=[digit.utils.validators.journal_entry_validator.validate_journal_entry]),
        ),
    ]
