# Generated by Django 4.2.9 on 2024-02-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=models.TextField(blank=True, help_text='The textual content of the journal entry.', null=True, verbose_name='Content'),
        ),
    ]
