# Generated by Django 4.2.6 on 2024-01-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='cleaned',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='fertilized',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='watered',
        ),
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=models.TextField(default='', help_text='The textual content of the journal entry.', verbose_name='Content'),
            preserve_default=False,
        ),
    ]
