# Generated by Django 5.0.2 on 2024-05-24 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitization', '0009_remove_userdigit_inventory_page_and_more'),
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={},
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='page',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='sort_order',
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='digit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='digitization.digitalobject'),
        ),
    ]
