# Generated by Django 5.0.2 on 2024-05-25 19:19

import base.utils.storage
import django.db.models.deletion
import journal.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_alter_journalentry_options_remove_journalentry_page_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Journal Entry Collection UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('digit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='journal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, storage=base.utils.storage.PublicMediaStorage(), upload_to=journal.models.journal_image_path)),
                ('caption', models.CharField(blank=True, help_text='Image caption.', max_length=250, null=True)),
                ('note', models.TextField(blank=True, help_text='Journal entry note.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='journal.entrycollection')),
            ],
        ),
        migrations.DeleteModel(
            name='JournalEntry',
        ),
    ]
