# Generated by Django 4.2.6 on 2024-01-31 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_remove_entry_cleaned_remove_entry_fertilized_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='collection',
            field=models.ForeignKey(help_text='The collection this journal entry belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='journal.collection'),
        ),
    ]
