# Generated by Django 5.0.2 on 2024-05-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_alter_entrycollection_digit'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entry_number',
            field=models.PositiveIntegerField(default=1, help_text='Entry number in the journal.'),
        ),
    ]
