# Generated by Django 4.2.9 on 2024-02-11 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_collection_digit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={},
        ),
    ]
