# Generated by Django 5.0.2 on 2024-05-25 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitization', '0012_rename_digital_object_digitalobjectpage_digit'),
        ('journal', '0003_entrycollection_entry_delete_journalentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrycollection',
            name='digit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal', to='digitization.digitalobject'),
        ),
    ]
