# Generated by Django 4.2.6 on 2024-02-01 22:09

import digidex.journal.models.entry
import digidex.utils.custom_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_alter_entry_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_thumbnail',
            field=models.BooleanField(default=False, help_text="Indicates if the entry's image is currently used as the thumbnail for the Collection.", verbose_name='Is Thumbnail'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='thumbnail',
            field=models.URLField(blank=True, help_text='URL of the thumbnail image for the digitized plant.', null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=models.ImageField(blank=True, help_text='(Optional) The image to save with the journal entry. Only .jpg, .png, and .jpeg extensions are allowed.', null=True, storage=digidex.utils.custom_storage.PrivateMediaStorage(), upload_to=digidex.journal.models.entry.journal_image_directory_path),
        ),
    ]
