# Generated by Django 5.0.2 on 2024-06-28 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('journal', '0003_remove_noteimagegallery_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='entry',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.digideximage'),
        ),
    ]
