# Generated by Django 5.0.2 on 2024-05-31 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_entry_entry_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrycollection',
            options={'verbose_name': 'Journal Entry Collection'},
        ),
    ]
