# Generated by Django 4.2.9 on 2024-02-11 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_alter_collection_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'Journal Collection', 'verbose_name_plural': 'Journal Collections'},
        ),
    ]
