# Generated by Django 4.2.6 on 2024-02-01 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_entry_is_thumbnail_alter_collection_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='thumbnail',
            field=models.URLField(blank=True, help_text='URL of the thumbnail image for the digitized plant.', max_length=500, null=True),
        ),
    ]
