# Generated by Django 5.0.2 on 2024-05-25 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitization', '0012_rename_digital_object_digitalobjectpage_digit'),
        ('journal', '0004_alter_entrycollection_digit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrycollection',
            name='digit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='journal', to='digitization.digitalobject'),
        ),
    ]
