# Generated by Django 4.2.9 on 2024-02-26 18:26

import digidex.journal.models.collection
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('journal', '0005_alter_collection_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='digit',
        ),
        migrations.AddField(
            model_name='collection',
            name='content_type',
            field=models.ForeignKey(default=digidex.journal.models.collection.get_default_content_type, help_text='The type of the digit associated with this journal collection.', limit_choices_to=models.Q(models.Q(('app_label', 'inventory'), ('model', 'plant')), models.Q(('app_label', 'inventory'), ('model', 'pet')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='collection',
            name='object_id',
            field=models.PositiveIntegerField(help_text='The ID of the digit associated with this journal collection.', null=True),
        ),
    ]
