# Generated by Django 4.2.6 on 2024-02-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_remove_entry_is_thumbnail_alter_collection_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entry_number',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Numeric value indicating the entry number within the collection.', verbose_name='Entry Number'),
        ),
    ]
