# Generated by Django 5.0.2 on 2024-06-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetnote',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='assetnote',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
