# Generated by Django 5.0.2 on 2024-06-26 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_alter_assetnote_options_assetnote_sort_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetpage',
            name='name',
        ),
    ]
