# Generated by Django 5.0.2 on 2024-06-27 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_delete_assetnearfieldcommunicationlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetnoteimagegallery',
            name='note',
        ),
        migrations.RemoveField(
            model_name='assetnoteimagegallery',
            name='noteimagegallery_ptr',
        ),
        migrations.DeleteModel(
            name='AssetNote',
        ),
        migrations.DeleteModel(
            name='AssetNoteImageGallery',
        ),
    ]
