# Generated by Django 5.0.2 on 2024-06-27 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_remove_assetnoteimagegallery_note_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetpage',
            options={'verbose_name': 'Digitized Asset Page'},
        ),
    ]
