# Generated by Django 5.0.2 on 2024-06-28 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_alter_assetpage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetpage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
