# Generated by Django 5.0.2 on 2024-07-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_alter_assetpage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetpage',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
