# Generated by Django 5.0.2 on 2024-03-24 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogindexpage_call_to_action_blogindexpage_heading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogindexpage',
            name='call_to_action',
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='call_to_action',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='blogtagindexpage',
            name='call_to_action',
        ),
        migrations.RemoveField(
            model_name='blogtagindexpage',
            name='heading',
        ),
    ]
