# Generated by Django 5.0.2 on 2024-04-11 00:43

import base.blocks
import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogindexpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogindexpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.StructBlock([('text', base.blocks.BasicCharBlock(required=True)), ('size', wagtail.blocks.ChoiceBlock(choices=[('', 'Select a heading size'), ('h1', 'H1'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4'), ('h5', 'H5'), ('h6', 'H6')]))])), ('paragraph', base.blocks.BasicParagraphBlock()), ('image', base.blocks.BasicImageBlock()), ('document', base.blocks.BasicDocumentBlock())], blank=True, null=True),
        ),
    ]
