# Generated by Django 5.0.2 on 2024-03-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpagegalleryimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='intro',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='heading_paragraph',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='heading_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
