# Generated by Django 5.0.6 on 2024-08-03 22:36

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_author_author_image_remove_author_name_and_more'),
        ('company', '0012_remove_team_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='authors',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='company.teammember'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
