# Generated by Django 5.0.2 on 2024-03-31 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_blogpage_intro_blogpage_heading_paragraph_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogindexpage',
            old_name='heading_paragraph',
            new_name='heading_intro',
        ),
        migrations.RenameField(
            model_name='blogpage',
            old_name='heading_paragraph',
            new_name='heading_intro',
        ),
    ]
