# Generated by Django 5.0.2 on 2024-04-02 23:41

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_heading_paragraph_blogindexpage_heading_intro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogindexpage',
            name='heading_intro',
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='heading_title',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='heading_intro',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='heading_title',
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='heading',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='heading',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
