# Generated by Django 5.0.2 on 2024-04-03 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_blogindexpage_heading_intro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogindexpage',
            name='heading',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='blogindexpage',
            name='intro',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='heading',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='intro',
            field=models.CharField(max_length=250),
        ),
    ]
