# Generated by Django 5.0.2 on 2024-04-04 03:10

import base.blocks.base
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_blogindexpage_heading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogindexpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', base.blocks.base.HeadingBlock()), ('paragraph', base.blocks.base.ParagraphBlock())], blank=True, null=True),
        ),
    ]
