# Generated by Django 5.0.2 on 2024-04-04 03:11

import base.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_blogindexpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogindexpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', base.blocks.HeadingBlock()), ('introduction', base.blocks.ParagraphBlock())], blank=True, null=True),
        ),
    ]
