# Generated by Django 4.1.7 on 2023-05-21 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('botany', '0003_'),
    ]

    operations = [
        migrations.CreateModel(
            name='Greenhouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('light_sensor', models.CharField(max_length=255)),
                ('temperature_sensor', models.CharField(max_length=255)),
                ('humidity_sensor', models.CharField(max_length=255)),
                ('air_speed_sensor', models.CharField(max_length=255)),
                ('ndir_co2_sensor', models.CharField(max_length=255)),
                ('voc_sensor', models.CharField(max_length=255)),
                ('floor_area', models.DecimalField(decimal_places=2, max_digits=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GreenhouseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('light_sensor', models.CharField(max_length=255)),
                ('temperature_sensor', models.CharField(max_length=255)),
                ('humidity_sensor', models.CharField(max_length=255)),
                ('air_speed_sensor', models.CharField(max_length=255)),
                ('ndir_co2_sensor', models.CharField(max_length=255)),
                ('voc_sensor', models.CharField(max_length=255)),
                ('object_id', models.PositiveIntegerField()),
                ('bench_area', models.DecimalField(decimal_places=2, max_digits=6)),
                ('eave_height', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ridge_height', models.DecimalField(decimal_places=2, max_digits=4)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cybotany.greenhouse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GrowthChamber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('light_sensor', models.CharField(max_length=255)),
                ('temperature_sensor', models.CharField(max_length=255)),
                ('humidity_sensor', models.CharField(max_length=255)),
                ('air_speed_sensor', models.CharField(max_length=255)),
                ('ndir_co2_sensor', models.CharField(max_length=255)),
                ('voc_sensor', models.CharField(max_length=255)),
                ('measurement_system', models.CharField(choices=[('in', 'Inches'), ('cm', 'Centimeters')], default='cm', max_length=2)),
                ('chamber_width', models.DecimalField(decimal_places=2, max_digits=6)),
                ('chamber_height', models.DecimalField(decimal_places=2, max_digits=6)),
                ('chamber_length', models.DecimalField(decimal_places=2, max_digits=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Plant',
        ),
    ]
