# Generated by Django 4.1.7 on 2023-05-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botany', '0005_remove_greenhousesection_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('camera', 'Camera'), ('light', 'Light'), ('fan', 'Fan')], max_length=10)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('temp', 'Temperature'), ('humidity', 'Humidity'), ('light', 'Light'), ('voc', 'Air Quality')], max_length=10)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='growthchamber',
            name='instruments',
            field=models.ManyToManyField(blank=True, to='cybotany.instrument'),
        ),
        migrations.AddField(
            model_name='growthchamber',
            name='sensors',
            field=models.ManyToManyField(blank=True, to='cybotany.sensor'),
        ),
    ]
