# Generated by Django 4.1.7 on 2023-06-11 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botany', '0009_label_plant_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='common_names',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='edible_parts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='gbif_species_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='propagation_methods',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='synonyms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='taxonomy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
