# Generated by Django 4.1.7 on 2023-06-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botany', '0010_plant_common_names_plant_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='url',
        ),
        migrations.AddField(
            model_name='plant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plants/'),
        ),
    ]
