# Generated by Django 4.1.7 on 2023-06-19 20:06

import apps.utils.helpers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('botany', '0011_remove_plant_url_plant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='is_common',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='label',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.utils.helpers.user_directory_path, validators=[apps.utils.helpers.validate_file_extension]),
        ),
        migrations.AlterUniqueTogether(
            name='label',
            unique_together={('name', 'user')},
        ),
    ]
