# Generated by Django 4.1.7 on 2023-06-21 04:32

import apps.utils.custom_storage
import apps.utils.helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botany', '0012_label_is_common_alter_label_name_alter_label_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='edible_parts',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='gbif_species_id',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='image',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='propagation_methods',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='scientific_name',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='synonyms',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='taxonomy',
        ),
        migrations.CreateModel(
            name='PlantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.utils.custom_storage.PlantImageStorage(apps.utils.helpers.user_directory_path), validators=[apps.utils.helpers.validate_file_extension])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='botany.plant')),
            ],
        ),
    ]
