# Generated by Django 4.1.7 on 2023-06-30 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botany', '0014_alter_label_options_remove_plant_common_names_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='owner',
            new_name='user',
        ),
    ]
