# Generated by Django 4.1.7 on 2023-07-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botany', '0015_rename_owner_plant_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GrowingMedium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('growing_methods', models.ManyToManyField(related_name='growing_mediums', to='botany.growingmethod')),
            ],
        ),
    ]
