# Generated by Django 4.1.7 on 2023-07-03 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('botany', '0016_growingmethod_growingmedium'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowingMediumComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(choices=[('Soil', 'Soil'), ('Coco Coir', 'Coco Coir'), ('Pine Coir', 'Pine Coir'), ('Rockwool', 'Rockwool'), ('LECA', 'LECA'), ('Perlite', 'Perlite'), ('Vermiculite', 'Vermiculite'), ('Calcined Clay', 'Calcined Clay'), ('Montmorillonite Clay', 'Montmorillonite Clay'), ('Sphagnum Moss', 'Sphagnum Moss'), ('Peat Moss', 'Peat Moss')], help_text='Components used as growing medium for plants.', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description for plant growing medium components.')),
                ('particle_size', models.DecimalField(blank=True, decimal_places=2, help_text='Particle size of the growing medium component.', max_digits=5, null=True)),
                ('particle_size_unit', models.CharField(blank=True, choices=[('in', 'Inches'), ('cm', 'Centimeters')], help_text='Unit of measurement for the particle size.', max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='growingmedium',
            name='growing_methods',
        ),
        migrations.AddField(
            model_name='growingmedium',
            name='description',
            field=models.TextField(blank=True, help_text='Description for the growing medium.'),
        ),
        migrations.AddField(
            model_name='plant',
            name='growing_medium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='botany.growingmedium'),
        ),
        migrations.AddField(
            model_name='plant',
            name='growing_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='botany.growingmethod'),
        ),
        migrations.AlterField(
            model_name='growingmedium',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the growing medium for plants.', max_length=100),
        ),
        migrations.AlterField(
            model_name='growingmethod',
            name='name',
            field=models.CharField(choices=[('Traditional', 'Traditional'), ('Hydroponics', 'Hydroponics')], help_text='Growing methods for plants.', max_length=100),
        ),
        migrations.CreateModel(
            name='GrowingMediumComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Percentage of the component in the growing medium.', max_digits=5)),
                ('component', models.ForeignKey(help_text='Reference to the component used in the growing medium.', on_delete=django.db.models.deletion.CASCADE, to='botany.growingmediumcomponent')),
                ('growing_medium', models.ForeignKey(help_text='Reference to the growing medium in which the component is used.', on_delete=django.db.models.deletion.CASCADE, to='botany.growingmedium')),
            ],
        ),
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Brand name of the fertilizer.', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the fertilizer.')),
                ('nitrogen', models.DecimalField(decimal_places=2, help_text='Percentage of nitrogen content in the fertilizer.', max_digits=5)),
                ('phosphorus', models.DecimalField(decimal_places=2, help_text='Percentage of phosphorus content in the fertilizer.', max_digits=5)),
                ('potassium', models.DecimalField(decimal_places=2, help_text='Percentage of potassium content in the fertilizer.', max_digits=5)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_on'],
            },
        ),
    ]
