# Generated by Django 4.1.7 on 2023-07-04 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botany', '0018_rename_component_growingmediumcomposition_growing_medium_component'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GrowingMediumComponent',
            new_name='GrowingComponent',
        ),
        migrations.RenameField(
            model_name='growingmediumcomposition',
            old_name='growing_medium_component',
            new_name='growing_component',
        ),
    ]
