# Generated by Django 4.1.7 on 2023-07-04 23:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('botany', '0019_rename_growingmediumcomponent_growingcomponent_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GrowingMediumComposition',
            new_name='GrowingComposition',
        ),
        migrations.RenameModel(
            old_name='Fertilizer',
            new_name='GrowingFertilizer',
        ),
        migrations.RenameModel(
            old_name='Label',
            new_name='GrowingLabel',
        ),
    ]
