# Generated by Django 4.1.7 on 2023-07-08 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('botany', '0020_rename_growingmediumcomposition_growingcomposition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='growingmedium',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
