# Generated by Django 4.1.7 on 2023-07-22 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botany', '0021_growingmedium_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this plant is active.'),
        ),
    ]
