# Generated by Django 4.1.7 on 2023-09-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botany', '0022_plant_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='nfc_tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='The quantity of the plant.'),
        ),
    ]
