# Generated by Django 4.1.7 on 2023-09-12 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botany', '0023_plant_nfc_tag_plant_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='growing_medium',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='growing_method',
        ),
    ]
