# Generated by Django 4.1.7 on 2023-09-13 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botany', '0024_remove_plant_growing_medium_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='label',
        ),
        migrations.AddField(
            model_name='plant',
            name='grouping',
            field=models.CharField(blank=True, choices=[('seed', 'Seed'), ('sprout', 'Sprout'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('discarded', 'Discarded')], help_text='The grouping of the plant.', max_length=50, null=True),
        ),
    ]
