# Generated by Django 4.1.7 on 2023-09-27 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botany', '0026_rename_uploaded_at_plantimage_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='grouping',
        ),
    ]
