# Generated by Django 4.1.7 on 2023-10-01 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itis', '0008_delete_jurisdiction_delete_vernaculars'),
        ('botany', '0027_remove_plant_grouping'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='tsn',
            field=models.ForeignKey(blank=True, help_text='The TSN of the plant in the ITIS database.', null=True, on_delete=django.db.models.deletion.CASCADE, to='itis.taxonomicunits'),
        ),
    ]
