# Generated by Django 4.1.7 on 2023-10-01 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botany', '0028_plant_tsn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='tsn',
        ),
    ]
