# Generated by Django 4.1.7 on 2023-10-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botany', '0029_remove_plant_tsn'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='tsn',
            field=models.PositiveIntegerField(blank=True, help_text='The TSN (Taxonomic Serial Number) of the plant.', null=True),
        ),
    ]
