# Generated by Django 4.1.7 on 2023-10-04 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botany', '0030_plant_tsn'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantwatering',
            name='duration_since_last_watering',
            field=models.DurationField(blank=True, help_text='Duration since the last watering event.', null=True),
        ),
    ]
