# Generated by Django 4.1.7 on 2023-10-04 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itis', '0008_delete_jurisdiction_delete_vernaculars'),
        ('botany', '0031_plantwatering_duration_since_last_watering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='tsn',
            field=models.ForeignKey(blank=True, help_text='The TSN (Taxonomic Serial Number) of the plant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plants', to='itis.taxonomicunits'),
        ),
    ]
