# Generated by Django 4.1.7 on 2023-10-07 02:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('botany', '0032_alter_plant_tsn'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantFertilization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertilized', models.BooleanField(default=False, help_text='Whether the plant was fertilized.')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time when the plant was fertilized.')),
                ('duration_since_last_fertilization', models.DurationField(blank=True, help_text='Duration since the last fertilization event.', null=True)),
                ('plant', models.ForeignKey(help_text='The plant associated with this fertilization event.', on_delete=django.db.models.deletion.CASCADE, related_name='fertilizations', to='botany.plant')),
            ],
        ),
    ]
