# Generated by Django 4.1.7 on 2023-11-04 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('botany', '0033_plantfertilization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the group.', max_length=50)),
                ('current_count', models.PositiveIntegerField(default=0, help_text='The current number of plants in this group.')),
                ('user', models.ForeignKey(blank=True, help_text='The user who created the group.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.DeleteModel(
            name='GrowingLabel',
        ),
        migrations.AddField(
            model_name='plant',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plants', to='botany.group'),
        ),
    ]
