# Generated by Django 4.1.7 on 2023-11-04 21:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('botany', '0034_group_delete_growinglabel_plant_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='The position/order of the group.'),
            preserve_default=False,
        ),
    ]
