# Generated by Django 4.1.7 on 2023-11-04 21:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('botany', '0035_alter_group_options_alter_group_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'group', 'verbose_name_plural': 'groups'},
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('name', 'user')},
        ),
    ]
