# Generated by Django 4.1.7 on 2023-11-04 22:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('botany', '0036_alter_group_options_alter_group_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='growingcomposition',
            name='growing_component',
        ),
        migrations.RemoveField(
            model_name='growingcomposition',
            name='growing_medium',
        ),
        migrations.RemoveField(
            model_name='growingfertilizer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='growingmedium',
            name='user',
        ),
        migrations.DeleteModel(
            name='GrowingMethod',
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['position'], 'verbose_name': 'group', 'verbose_name_plural': 'groups'},
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('position', 'user'), ('name', 'user')},
        ),
        migrations.DeleteModel(
            name='GrowingComponent',
        ),
        migrations.DeleteModel(
            name='GrowingComposition',
        ),
        migrations.DeleteModel(
            name='GrowingFertilizer',
        ),
        migrations.DeleteModel(
            name='GrowingMedium',
        ),
    ]
