# Generated by Django 4.2.6 on 2023-11-13 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botany', '0037_remove_growingcomposition_growing_component_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantJournaling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='The date and time when the journal entry was made.')),
                ('notes', models.TextField(help_text='Notes or details about the plant.')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='botany.plant')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
