# Generated by Django 4.2.6 on 2023-11-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botany', '0038_plantjournaling'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlantJournaling',
            new_name='PlantJournal',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='nfc_tag',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='user',
        ),
        migrations.AlterField(
            model_name='plant',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='The plant quantity.'),
        ),
    ]
