# Generated by Django 4.2.6 on 2023-11-23 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botany', '0039_rename_plantjournaling_plantjournal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='group',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='tsn',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
