# Generated by Django 4.1.7 on 2023-06-03 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowthChamber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('measurement_system', models.CharField(choices=[('in', 'Inches'), ('cm', 'Centimeters')], default='cm', max_length=2)),
                ('chamber_width', models.DecimalField(decimal_places=2, max_digits=6)),
                ('chamber_height', models.DecimalField(decimal_places=2, max_digits=6)),
                ('chamber_length', models.DecimalField(decimal_places=2, max_digits=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
