# Generated by Django 4.1.7 on 2023-06-11 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cea', '0002_remove_growthchamber_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowthChamberInstrumentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pressure', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('growth_chamber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='cea.growthchamber')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
