# Generated by Django 4.1.7 on 2023-06-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cea', '0003_growthchamberinstrumentdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenhouse',
            name='identifier',
            field=models.CharField(default='TEST', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='growthchamber',
            name='identifier',
            field=models.CharField(default='TEST', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tissueculturechamber',
            name='identifier',
            field=models.CharField(default='TEST', max_length=255),
            preserve_default=False,
        ),
    ]
