# Generated by Django 5.0.2 on 2024-06-24 00:06

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landingpage',
            options={'verbose_name': 'Landing Page', 'verbose_name_plural': 'Landing Page'},
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='hero_heading',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='hero_paragraph',
        ),
        migrations.AddField(
            model_name='landingpage',
            name='content',
            field=wagtail.fields.StreamField([('content', wagtail.blocks.StructBlock([('heading', wagtail.blocks.StructBlock([('subtitle', wagtail.blocks.CharBlock(form_classname='title', required=False)), ('title', wagtail.blocks.CharBlock(form_classname='title', required=True))])), ('grid', wagtail.blocks.StructBlock([])), ('footnote', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(required=False)), ('link', wagtail.blocks.StructBlock([('url', wagtail.blocks.URLBlock(help_text='Enter the URL to link to', required=True)), ('text', wagtail.blocks.CharBlock(help_text='Enter the text to display', required=True))], required=True))]))]))], blank=True),
        ),
    ]
