# Generated by Django 5.0.6 on 2024-08-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_body',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='hero body'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_heading',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='hero heading'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='primary_cta_text',
            field=models.CharField(default='Get Started', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='primary_cta_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='secondary_cta_text',
            field=models.CharField(default='Learn More', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='secondary_cta_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
