# Generated by Django 5.0.6 on 2024-08-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_homepage_body_homepage_hero_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='primary_cta_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='secondary_cta_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
