# Generated by Django 5.0.2 on 2024-03-27 20:23

import base.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_homepage_options_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('page_heading', wagtail.blocks.StructBlock([('heading', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(help_text='Add your text here', required=True))])), ('text', wagtail.blocks.CharBlock(required=False))], required=False)), ('page_body', wagtail.blocks.StreamBlock([('heading', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(help_text='Add your text here', required=True))])), ('paragraph', base.blocks._RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('button', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(required=True)), ('link', wagtail.blocks.URLBlock(required=False))])), ('grid', wagtail.blocks.StreamBlock([('heading', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(help_text='Add your text here', required=True))])), ('color', wagtail.blocks.StructBlock([('color', wagtail.blocks.ChoiceBlock(choices=[('white', 'White'), ('background', 'Background'), ('border', 'Border'), ('heading-color', 'Heading'), ('accent-a1', 'Accent A1'), ('accent-a2', 'Accent A2'), ('accent-a3', 'Accent A3'), ('accent-a4', 'Accent A4'), ('accent-b1', 'Accent B1'), ('accent-b2', 'Accent B2'), ('accent-b3', 'Accent B3'), ('paragraph-color', 'Paragraph')], help_text='Select a color scheme')), ('title', wagtail.blocks.CharBlock(help_text='Enter the title text', required=True)), ('subtitle', wagtail.blocks.CharBlock(help_text='Enter the subtitle text', required=True))]))]))]))], blank=True, null=True),
        ),
    ]
