# Generated by Django 5.0.2 on 2024-03-31 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_homepage_options_homepage_body_and_more'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='heading',
            new_name='hero_heading',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='paragraph',
            new_name='hero_paragraph',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.AddField(
            model_name='homepage',
            name='alt_hero_cta_link',
            field=models.ForeignKey(blank=True, help_text='Choose a page to link to for the Alternate Call to Action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Alternate Hero CTA link'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_link',
            field=models.ForeignKey(blank=True, help_text='Choose a page to link to for the Primary Call to Action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Primary Hero CTA link'),
        ),
    ]
