# Generated by Django 5.0.2 on 2024-05-08 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_userprofileindexpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileIndexPage',
        ),
    ]
