# Generated by Django 5.0.6 on 2024-07-21 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepage_options_adminpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminpage',
            options={'verbose_name': 'admin page'},
        ),
    ]
