# Generated by Django 5.0.2 on 2024-04-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_heading_homepage_hero_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='alt_hero_cta_text',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_text',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='alt_hero_cta_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_cta_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
