# Generated by Django 5.0.2 on 2024-05-17 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_userprofileindexpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
    ]
