# Generated by Django 5.0.2 on 2024-03-24 03:07

import base.fields.wagtail
import wagtail.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_call_to_action_homepage_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='call_to_action',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='solutions',
        ),
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=base.fields.wagtail.BaseStreamField([('hero', wagtail.blocks.StructBlock([])), ('solutions', wagtail.blocks.StructBlock([])), ('company', wagtail.blocks.StructBlock([])), ('features', wagtail.blocks.StructBlock([])), ('reviews', wagtail.blocks.StructBlock([])), ('support', wagtail.blocks.StructBlock([])), ('faq', wagtail.blocks.StructBlock([])), ('cta', wagtail.blocks.StructBlock([]))], default=[]),
        ),
    ]
