# Generated by Django 5.0.2 on 2024-06-24 14:37

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_landingpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='body',
            field=wagtail.fields.StreamField([('style', wagtail.blocks.ChoiceBlock(choices=[('', 'Default')])), ('section', wagtail.blocks.StructBlock([('heading', wagtail.blocks.StructBlock([('subtitle', wagtail.blocks.CharBlock(form_classname='title', required=False)), ('title', wagtail.blocks.CharBlock(form_classname='title', required=True))], required=False)), ('footnote', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(required=False)), ('link', wagtail.blocks.StructBlock([('url', wagtail.blocks.URLBlock(help_text='Enter the URL to link to', required=True)), ('text', wagtail.blocks.CharBlock(help_text='Enter the text to display', required=True))], required=True))], required=False))]))], blank=True),
        ),
    ]
