# Generated by Django 5.0.6 on 2024-07-21 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_adminpage_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminPage',
        ),
    ]
