# Generated by Django 5.0.2 on 2024-03-28 04:17

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home Page', 'verbose_name_plural': 'Home Pages'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='heading_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='heading_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('content', wagtail.blocks.StreamBlock([('heading', wagtail.blocks.CharBlock(max_length=255, required=False)), ('paragraph', wagtail.blocks.RichTextBlock()), ('figure', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('caption', wagtail.blocks.CharBlock(help_text='Add a caption for the image', required=False))])), ('buttons', wagtail.blocks.StructBlock([('primary', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(max_length=255, required=True)), ('url', wagtail.blocks.URLBlock(required=True)), ('size', wagtail.blocks.ChoiceBlock(choices=[('button', 'Primary'), ('button-small', 'Small')], help_text='Select button size')), ('style', wagtail.blocks.ChoiceBlock(choices=[('', 'Primary'), ('dark', 'Dark'), ('yellow', 'Yellow'), ('-outline', 'Outline')], help_text='Select button style'))])), ('secondary', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(max_length=255, required=True)), ('url', wagtail.blocks.URLBlock(required=True)), ('size', wagtail.blocks.ChoiceBlock(choices=[('button', 'Primary'), ('button-small', 'Small')], help_text='Select button size')), ('style', wagtail.blocks.ChoiceBlock(choices=[('', 'Primary'), ('dark', 'Dark'), ('yellow', 'Yellow'), ('-outline', 'Outline')], help_text='Select button style'))]))])), ('digits', wagtail.blocks.StreamBlock([('digits', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('style', wagtail.blocks.ChoiceBlock(choices=[('white', 'White'), ('background', 'Background'), ('border', 'Border'), ('heading-color', 'Heading'), ('accent-a1', 'Accent A1'), ('accent-a2', 'Accent A2'), ('accent-a3', 'Accent A3'), ('accent-a4', 'Accent A4'), ('accent-b1', 'Accent B1'), ('accent-b2', 'Accent B2'), ('accent-b3', 'Accent B3'), ('paragraph-color', 'Paragraph')], help_text='Select a color scheme')), ('title', wagtail.blocks.CharBlock(help_text='Enter the title', required=True)), ('subtitle', wagtail.blocks.CharBlock(help_text='Enter the subtitle', required=False))])))]))]))], blank=True),
        ),
    ]
