# Generated by Django 5.0.2 on 2024-04-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_alt_hero_cta_text_homepage_hero_cta_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='alt_hero_cta_text',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_cta_text',
            field=models.CharField(blank=True, null=True),
        ),
    ]
