# Generated by Django 5.0.2 on 2024-04-02 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_homepage_alt_hero_cta_text_and_more'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='alt_hero_cta_text',
            new_name='alt_cta_text',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='hero_cta_text',
            new_name='cta_text',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='hero_heading',
            new_name='heading',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='hero_paragraph',
            new_name='paragraph',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='alt_hero_cta_link',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_cta_link',
        ),
        migrations.AddField(
            model_name='homepage',
            name='alt_cta_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
