# Generated by Django 5.0.6 on 2024-07-22 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_adminpage'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePage',
            new_name='DigiDexHomePage',
        ),
        migrations.AlterModelOptions(
            name='digidexhomepage',
            options={'verbose_name': 'digidex homepage'},
        ),
    ]
