# Generated by Django 5.0.2 on 2024-04-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_homepage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Hero Heading'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_paragraph',
            field=models.TextField(blank=True, verbose_name='Hero Paragraph'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_primary_cta_link',
            field=models.URLField(blank=True, verbose_name='Primary CTA Link'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_primary_cta_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Primary CTA Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_secondary_cta_link',
            field=models.URLField(blank=True, verbose_name='Secondary CTA Link'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_secondary_cta_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Secondary CTA Text'),
        ),
    ]
