# Generated by Django 5.0.2 on 2024-04-21 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_homepage_body_homepage_hero_heading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='hero_primary_cta_link',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_primary_cta_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_secondary_cta_link',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_secondary_cta_text',
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_link',
            field=models.URLField(blank=True, verbose_name='Hero CTA Link'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Hero CTA Text'),
        ),
    ]
