# Generated by Django 5.0.6 on 2024-07-22 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_homepage_digidexhomepage_and_more'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DigiDexHomePage',
            new_name='HomePage',
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'homepage'},
        ),
    ]
