# Generated by Django 5.0.2 on 2024-04-02 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_alt_hero_cta_text_homepage_alt_cta_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='feature_1',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='feature_2',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='feature_3',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='feature_4',
            field=models.CharField(blank=True, null=True),
        ),
    ]
