# Generated by Django 5.0.2 on 2024-03-25 20:34

import digidex.base.blocks._basics
import base.fields.wagtail
import wagtail.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=base.fields.wagtail.BaseStreamField([('hero', wagtail.blocks.StructBlock([('content', wagtail.blocks.StreamBlock([('grid', wagtail.blocks.StreamBlock([('blocks', wagtail.blocks.StreamBlock([('cta', wagtail.blocks.StructBlock([('promo', wagtail.blocks.StructBlock([('page', base.blocks._basics.BasePageBlock(help_text='Select the page to link to for the promo', required=True)), ('text', base.blocks._basics.BaseRichTextBlock(help_text='Enter the text for the promo', required=True))], required=False)), ('heading', wagtail.blocks.StructBlock([('title', base.blocks._basics.BaseCharBlock(help_text='Enter the heading title', required=True)), ('subtitle', base.blocks._basics.BaseCharBlock(help_text='Enter the heading subtitle', required=False)), ('text', base.blocks._basics.BaseTextBlock(help_text='Enter the heading text', required=False))])), ('buttons', wagtail.blocks.StructBlock([('primary', wagtail.blocks.StructBlock([('text', base.blocks._basics.BaseCharBlock(help_text='Text for the button', required=True)), ('url', base.blocks._basics.BaseURLBlock(help_text='URL the button will link to', required=True))], help_text='Primary button', required=True)), ('secondary', wagtail.blocks.StructBlock([('text', base.blocks._basics.BaseCharBlock(help_text='Text for the button', required=True)), ('url', base.blocks._basics.BaseURLBlock(help_text='URL the button will link to', required=True)), ('icon', base.blocks._basics.BaseImageBlock())], help_text='Secondary button', required=False))]))])), ('lottie', wagtail.blocks.StructBlock([('lines_a', base.blocks._basics.BaseListBlock(wagtail.blocks.StructBlock([('width', base.blocks._basics.BaseCharBlock(default='1px', help_text='Line width')), ('height', base.blocks._basics.BaseCharBlock(default='1px', help_text='Line height')), ('css_class', wagtail.blocks.ChoiceBlock(choices=[('line-w', 'Width line'), ('line-h', 'Height line')]))]), help_text='Vertical lines configuration')), ('lines_b', base.blocks._basics.BaseListBlock(wagtail.blocks.StructBlock([('width', base.blocks._basics.BaseCharBlock(default='1px', help_text='Line width')), ('height', base.blocks._basics.BaseCharBlock(default='1px', help_text='Line height')), ('css_class', wagtail.blocks.ChoiceBlock(choices=[('line-w', 'Width line'), ('line-h', 'Height line')]))]), help_text='Horizontal lines configuration')), ('animations', base.blocks._basics.BaseListBlock(wagtail.blocks.StructBlock([('animation_type', wagtail.blocks.ChoiceBlock(choices=[('lottie', 'Lottie')])), ('animation_src', base.blocks._basics.BaseDocumentBlock(required=True)), ('loop', base.blocks._basics.BaseBooleanBlock(help_text='Loop animation', required=False)), ('direction', base.blocks._basics.BaseIntegerBlock(default=1, help_text='Animation direction')), ('autoplay', base.blocks._basics.BaseBooleanBlock(help_text='Autoplay animation', required=False)), ('renderer', wagtail.blocks.ChoiceBlock(choices=[('svg', 'SVG')])), ('default_duration', base.blocks._basics.BaseFloatBlock(help_text='Default duration', required=False)), ('duration', base.blocks._basics.BaseFloatBlock(help_text='Duration', required=False))]), help_text='List of Lottie animations'))]))]))]))]))]))], default=[]),
        ),
    ]
