# Generated by Django 5.0.2 on 2024-03-21 07:45

import base.blocks.basic_blocks
import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_content',
            field=wagtail.fields.StreamField([('hero_section', wagtail.blocks.StructBlock([('content', wagtail.blocks.StructBlock([('items', wagtail.blocks.StreamBlock([('block', wagtail.blocks.StructBlock([('heading', base.blocks.basic_blocks.BaseCharBlock(max_length=75, required=True)), ('text', base.blocks.basic_blocks.BaseCharBlock(max_length=150, required=False)), ('call_to_action', wagtail.blocks.StructBlock([('text', base.blocks.basic_blocks.BaseCharBlock(help_text='Enter the link title')), ('url', base.blocks.basic_blocks.BaseURLBlock(help_text='Enter the URL', required=True)), ('target', wagtail.blocks.ChoiceBlock(choices=[('_self', 'Same window'), ('_blank', 'New window')], help_text='Where the link should open', required=False))], required=True))])), ('lottie', wagtail.blocks.StructBlock([('lottie_features', base.blocks.basic_blocks.BaseListBlock(wagtail.blocks.StructBlock([('order', wagtail.blocks.ChoiceBlock(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth')])), ('icon', base.blocks.basic_blocks.BaseImageBlock(required=True)), ('text', base.blocks.basic_blocks.BaseCharBlock(required=True))]), max_length=4))]))], min_num=1))]))]))], blank=True, help_text='Content for the hero section of the homepage.', null=True),
        ),
    ]
