# Generated by Django 5.0.2 on 2024-04-02 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homepage_feature_1_homepage_feature_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='alt_cta_link',
            new_name='cta_link_primary',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='cta_link',
            new_name='cta_link_secondary',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='alt_cta_text',
            new_name='cta_text_primary',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='cta_text',
            new_name='cta_text_secondary',
        ),
    ]
