# Generated by Django 5.0.2 on 2024-03-21 14:06

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_homepage_hero_content'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='hero_content',
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta',
            field=models.CharField(blank=True, help_text='Text to display on Call to Action', max_length=75, verbose_name='Hero CTA'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_link',
            field=models.ForeignKey(blank=True, help_text='Choose a page to link to for the Call to Action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Hero CTA link'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_heading',
            field=models.CharField(blank=True, help_text='Write an introduction for the site', max_length=75),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_text',
            field=models.CharField(blank=True, help_text='Write an introduction for the site', max_length=150),
        ),
        migrations.AddField(
            model_name='homepage',
            name='lottie',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
