# Generated by Django 5.0.2 on 2024-04-22 15:41

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_lottiefeature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottiefeature',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='lottie_features', to='home.homepage'),
        ),
    ]
