# Generated by Django 5.0.2 on 2024-04-02 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_alt_cta_link_homepage_cta_link_primary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='cta_link_primary',
            new_name='cta_link',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='cta_text_primary',
            new_name='cta_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='cta_link_secondary',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='cta_text_secondary',
        ),
    ]
