# Generated by Django 5.0.2 on 2024-04-05 20:24

import base.blocks.basic
import base.blocks.lottie
import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_cta_link_primary_homepage_cta_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='cta_link',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='cta_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='feature_1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='feature_2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='feature_3',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='feature_4',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='paragraph',
        ),
        migrations.AddField(
            model_name='homepage',
            name='page',
            field=wagtail.fields.StreamField([('hero_section', wagtail.blocks.StreamBlock([('heading', base.blocks.basic.HeadingBlock()), ('introduction', base.blocks.basic.ParagraphBlock()), ('button', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(required=True)), ('text', wagtail.blocks.CharBlock(required=True))])), ('lottie', wagtail.blocks.StructBlock([('lines', wagtail.blocks.StructBlock([('vertical', base.blocks.lottie.VerticalLines(help_text='Number of vertical lines.', required=False)), ('horizontal', base.blocks.lottie.HorizontalLines(help_text='Number of horizontal lines.', required=False))])), ('animation', base.blocks.lottie.LottieAnimation()), ('features', base.blocks.lottie.FeatureList())]))]))], blank=True, null=True),
        ),
    ]
