# Generated by Django 5.0.2 on 2024-04-23 00:12

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_lottiefeature_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('heading', models.CharField(blank=True, max_length=75)),
                ('subtitle', models.CharField(blank=True, max_length=25)),
                ('paragraph', models.CharField(blank=True, max_length=255)),
                ('content', wagtail.fields.RichTextField(blank=True)),
                ('style', models.CharField(blank=True, choices=[('section', 'Default'), ('section-top-bar', 'Top Bar'), ('section-hero', 'Hero'), ('section-footer', 'Footer'), ('section-top', 'Top'), ('section-full', 'Full')], default='default', max_length=15)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='home.homepage')),
            ],
            options={
                'verbose_name': 'section',
                'verbose_name_plural': 'sections',
            },
        ),
    ]
