# Generated by Django 5.0.2 on 2024-04-05 21:36

import base.blocks.basic
import base.blocks.lottie
import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_homepage_cta_link_remove_homepage_cta_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='page',
        ),
        migrations.AddField(
            model_name='homepage',
            name='section',
            field=wagtail.fields.StreamField([('hero', wagtail.blocks.StreamBlock([('heading', base.blocks.basic.Heading()), ('introduction', base.blocks.basic.Paragraph()), ('button', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(required=True)), ('text', wagtail.blocks.CharBlock(required=False))])), ('lottie', wagtail.blocks.StructBlock([('lines', wagtail.blocks.StructBlock([('vertical', base.blocks.lottie.VerticalLines(help_text='Number of vertical lines.', required=False)), ('horizontal', base.blocks.lottie.HorizontalLines(help_text='Number of horizontal lines.', required=False))])), ('animation', base.blocks.lottie.LottieAnimation()), ('features', base.blocks.lottie.FeatureList())]))]))], blank=True, null=True),
        ),
    ]
