# Generated by Django 5.0.2 on 2024-04-23 01:57

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_homepagesection_style'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='company_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Company Heading'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='company_paragraph',
            field=models.TextField(blank=True, verbose_name='Company Paragraph'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='company_subtitle',
            field=models.CharField(blank=True, max_length=255, verbose_name='Company Subtitle'),
        ),
        migrations.CreateModel(
            name='CompanyStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('heading', models.CharField(blank=True, max_length=25)),
                ('text', models.CharField(blank=True, max_length=75)),
                ('color', models.CharField(blank=True, max_length=25)),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_statistics', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='HomePageSection',
        ),
    ]
