# Generated by Django 5.0.2 on 2024-04-05 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_homepage_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='section',
            new_name='hero',
        ),
    ]
