# Generated by Django 5.0.2 on 2024-04-23 01:58

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_homepage_company_heading_homepage_company_paragraph_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottiefeature',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_features', to='home.homepage'),
        ),
    ]
