# Generated by Django 5.0.2 on 2024-04-23 04:15

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_lottiefeature_page'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='feature_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Feature Heading'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='feature_subtitle',
            field=models.CharField(blank=True, max_length=255, verbose_name='Feature Subtitle'),
        ),
        migrations.AlterField(
            model_name='companystatistic',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_statistic', to='home.homepage'),
        ),
        migrations.AlterField(
            model_name='lottiefeature',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='lottie_feature', to='home.homepage'),
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('heading', models.CharField(max_length=255)),
                ('paragraph', models.CharField(max_length=255)),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature', to='home.homepage')),
            ],
            options={
                'verbose_name': 'Product Feature',
                'verbose_name_plural': 'Product Features',
            },
        ),
    ]
