# Generated by Django 5.0.2 on 2024-04-23 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_solutionitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solutionitem',
            old_name='title',
            new_name='heading',
        ),
        migrations.RenameField(
            model_name='solutionitem',
            old_name='description',
            new_name='paragraph',
        ),
        migrations.RenameField(
            model_name='solutionitem',
            old_name='link_url',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='solutionitem',
            name='image',
        ),
    ]
