# Generated by Django 4.2.6 on 2024-01-02 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, help_text='The unique identifier associated with the NFC tag or identification mechanism.', max_length=255, unique=True, verbose_name='Tag UID')),
                ('active', models.BooleanField(default=False, help_text='Indicates whether the link is currently active and mapped to a digital object.', verbose_name='Active')),
                ('counter', models.IntegerField(default=0, help_text='The numerical counter value associated with the NFC tag.', verbose_name='Counter Value')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
            },
        ),
    ]
