# Generated by Django 4.2.6 on 2024-01-03 20:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nfc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date and time when the link instance was created.', verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, help_text='The date and time when the link instance was last modified.', verbose_name='Last Modified'),
        ),
    ]
