# Generated by Django 4.2.6 on 2023-11-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfc', '0002_tag_delete_nfctag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='tag',
            name='last_viewed',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Viewed'),
        ),
        migrations.AddField(
            model_name='tag',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='View Count'),
        ),
    ]
