# Generated by Django 4.2.6 on 2024-01-04 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfc', '0002_link_created_at_link_last_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='counter',
        ),
    ]
