# Generated by Django 4.2.6 on 2024-01-05 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nfc', '0003_remove_link_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='counter',
            field=models.IntegerField(default=0, help_text='The number of times the tag has been scanned.', verbose_name='Counter'),
        ),
        migrations.AddField(
            model_name='link',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user associated with this link.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
