# Generated by Django 4.2.6 on 2023-11-23 15:30

from django.db import migrations, models
import django.db.models.deletion
import uuid

def gen_uuid(apps, schema_editor):
    Tag = apps.get_model('nfc', 'Tag')
    for tag in Tag.objects.all():
        tag.uuid = uuid.uuid4()
        tag.save()


class Migration(migrations.Migration):

    dependencies = [
        ('nfc', '0003_remove_tag_updated_at_tag_last_viewed_tag_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID'),
        ),
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
