# Generated by Django 4.2.6 on 2023-11-24 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botany', '0040_remove_plant_group_remove_plant_tsn_delete_group'),
        ('nfc', '0005_tag_group_alter_tag_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='last_viewed',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='view_count',
        ),
        migrations.AlterField(
            model_name='tag',
            name='plant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='botany.plant', verbose_name='Associated Plant'),
        ),
    ]
