# Generated by Django 4.2.6 on 2023-11-24 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfc', '0005_tag_group_alter_tag_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='last_viewed',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='view_count',
        ),
    ]
