# Generated by Django 4.1.7 on 2023-09-29 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itis', '0002_delete_comments_delete_experts_delete_nodc_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hierarchy',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='geographicdivision',
            name='tsn',
            field=models.IntegerField(verbose_name='Taxonomic Serial Number'),
        ),
    ]
