# Generated by Django 4.1.7 on 2023-09-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itis', '0003_hierarchy_id_alter_geographicdivision_tsn'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonunittypes',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taxonunittypes',
            name='rank_id',
            field=models.SmallIntegerField(verbose_name='Rank ID'),
        ),
    ]
