# Generated by Django 4.1.7 on 2023-09-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itis', '0004_taxonunittypes_id_alter_taxonunittypes_rank_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxonomicunits',
            old_name='usage',
            new_name='n_usage',
        ),
        migrations.AddField(
            model_name='taxonomicunits',
            name='unnamed_taxon_ind',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
