# Generated by Django 4.1.7 on 2023-09-30 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itis', '0005_rename_usage_taxonomicunits_n_usage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxonomicunits',
            old_name='phylo_sort_sequence',
            new_name='phylo_sort_seq',
        ),
    ]
