# Generated by Django 4.1.7 on 2023-10-01 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itis', '0006_rename_phylo_sort_sequence_taxonomicunits_phylo_sort_seq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Longnames',
        ),
    ]
