# Generated by Django 4.1.7 on 2023-10-01 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itis', '0007_delete_longnames'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jurisdiction',
        ),
        migrations.DeleteModel(
            name='Vernaculars',
        ),
    ]
