# Generated by Django 4.1.7 on 2023-10-08 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itis', '0008_delete_jurisdiction_delete_vernaculars'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeographicDivision',
        ),
    ]
