# Generated by Django 4.2.6 on 2023-10-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itis', '0012_delete_hierarchy'),
    ]

    operations = [
    ]
