# Generated by Django 4.2.6 on 2023-11-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itis', '0015_alter_taxonunittypes_direct_parent_rank_id_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='taxonomicunits',
            index=models.Index(fields=['complete_name'], name='itis_taxono_complet_95ae36_idx'),
        ),
    ]
