# Generated by Django 4.2.6 on 2023-11-25 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0005_alter_hierarchy_options_and_more'),
        ('inventory', '0003_rename_created_by_link_user_alter_group_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Digitization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digitization', to='inventory.link')),
                ('taxonomic_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digitizations', to='taxonomy.unit')),
            ],
            options={
                'verbose_name': 'Digitization',
                'verbose_name_plural': 'Digitizations',
            },
        ),
    ]
