# Generated by Django 4.2.6 on 2023-11-26 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0007_kingdomrank_rank_remove_unit_kingdom_id_and_more'),
        ('inventory', '0003_rename_created_by_link_user_alter_group_user_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Digit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digit', to='inventory.link')),
                ('taxonomic_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digits', to='taxonomy.unit')),
            ],
            options={
                'verbose_name': 'Digit',
                'verbose_name_plural': 'Digits',
            },
        ),
        migrations.DeleteModel(
            name='Digitization',
        ),
    ]
