# Generated by Django 4.2.6 on 2023-11-27 02:29

import apps.utils.custom_storage
import apps.utils.helpers.get_user_directory_path
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_digit_delete_digitization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('entry', models.TextField(verbose_name='Content')),
                ('image', models.ImageField(help_text='The image file. Only .jpg, .png, and .jpeg extensions are allowed.', upload_to=apps.utils.custom_storage.JournalImageStorage(apps.utils.helpers.get_user_directory_path))),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('digit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='core.digit')),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
