# Generated by Django 4.2.6 on 2023-11-27 02:40

import apps.utils.custom_storage
import apps.utils.helpers.get_path
import apps.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='image',
            field=models.ImageField(blank=True, help_text='(Optional) The image to save with a journal entry. Only .jpg, .png, and .jpeg extensions are allowed.', null=True, upload_to=apps.utils.custom_storage.JournalImageStorage(apps.utils.helpers.get_user_directory_path), validators=[apps.utils.validators.validate_image_size_and_dimensions]),
        ),
    ]
