# Generated by Django 4.2.6 on 2023-12-03 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0009_delete_kingdomrank'),
        ('core', '0005_remove_journal_created_by_digit_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digit',
            name='taxonomic_unit',
            field=models.ForeignKey(blank=True, help_text='The taxonomic classification of the digitized plant.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='digits', to='taxonomy.unit'),
        ),
    ]
