# Generated by Django 4.2.6 on 2024-01-01 21:33

import apps.utils.custom_storage
import apps.utils.helpers.get_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_digit_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digit',
            name='description',
            field=models.TextField(blank=True, help_text='A short description of the digitized plant.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='image',
            field=models.ImageField(blank=True, help_text='(Optional) The image to save with the journal entry. Only .jpg, .png, and .jpeg extensions are allowed.', null=True, upload_to=apps.utils.custom_storage.JournalImageStorage(apps.utils.helpers.get_path.get_user_directory_path)),
        ),
    ]
