# Generated by Django 4.2.6 on 2024-01-02 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_digit_description_alter_journal_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digit',
            name='taxonomic_unit',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='digit',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='user',
        ),
    ]
