# Generated by Django 4.2.6 on 2024-01-02 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_digit_taxonomic_unit_remove_journal_digit_and_more'),
        ('inventory', '0011_digit_journal_delete_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Digit',
        ),
        migrations.DeleteModel(
            name='Journal',
        ),
    ]
