# Generated by Django 4.2.6 on 2024-01-22 04:36

import inventory.models.digit
import utils.validators.digit_thumbnail_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='digit',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail image for the digitized plant.', null=True, upload_to=inventory.models.digit.digit_thumbnail_directory_path, validators=[utils.validators.digit_thumbnail_validator.validate_digit_thumbnail]),
        ),
    ]
