# Generated by Django 4.1.7 on 2023-07-09 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='content',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='user',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='message',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='session_id',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
