# Generated by Django 4.1.7 on 2023-07-10 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_chatsession_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='session',
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
    ]
