# Generated by Django 4.1.7 on 2023-09-08 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_chathistory_rename_message_chatmessage_content_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatHistory',
        ),
    ]
