# Generated by Django 4.1.7 on 2023-03-17 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
