# Generated by Django 4.1.7 on 2023-05-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybotany', '0006_instrument_sensor_growthchamber_instruments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='description',
            field=models.TextField(default='No description provided.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='description',
            field=models.TextField(default='No description provided.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='max_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='min_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='value_unit',
            field=models.CharField(default='in', max_length=255),
            preserve_default=False,
        ),
    ]
