from .digit_detail_view import DigitDetailView
from .digit_storage_view import DigitStorageView
from .digit_creation_view import DigitCreationView
from .digit_deletion_view import DigitDeletionView
from .digit_modification_view import DigitModificationView
