# Generated by Django 5.0.2 on 2024-04-01 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('heading_title', models.CharField(blank=True, max_length=255, null=True)),
                ('heading_intro', models.CharField(blank=True, max_length=255, null=True)),
                ('body_heading_subtitle', models.CharField(blank=True, null=True)),
                ('body_heading_title', models.CharField(blank=True, null=True)),
                ('support_launch_chat', models.TextField(blank=True, null=True)),
                ('support_chat', models.CharField(blank=True, max_length=255, null=True)),
                ('support_launch_email', models.TextField(blank=True, null=True)),
                ('support_email', models.CharField(blank=True, max_length=255, null=True)),
                ('support_launch_call', models.TextField(blank=True, null=True)),
                ('support_call', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
