# Generated by Django 5.0.2 on 2024-03-22 08:23

import base.blocks.basics
import base.fields.django_fields
import base.fields.wagtail_fields
import django.db.models.deletion
import wagtail.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', base.fields.wagtail_fields.BaseStreamField([('paragraph', base.blocks.basics.BaseRichTextBlock())], blank=True, null=True)),
                ('intro_heading', base.fields.django_fields.BaseCharField(max_length=75)),
                ('intro_text', base.fields.django_fields.BaseTextField(max_length=150)),
                ('contact_options', base.fields.wagtail_fields.BaseStreamField([('contact_option', wagtail.blocks.StructBlock([('icon', base.blocks.basics.BaseImageBlock(required=True)), ('method', base.blocks.basics.BaseCharBlock(required=True)), ('detail', base.blocks.basics.BaseCharBlock(required=True)), ('link', base.blocks.basics.BaseURLBlock(required=False))]))], blank=True, null=True)),
                ('faqs', base.fields.wagtail_fields.BaseStreamField([('faq', wagtail.blocks.StructBlock([('question', base.blocks.basics.BaseCharBlock(required=True)), ('answer', base.blocks.basics.BaseTextBlock(required=True))]))], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
