# Generated by Django 5.0.2 on 2024-03-23 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupportIndexPage',
        ),
    ]
