# Generated by Django 5.0.2 on 2024-04-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, help_text='Support Email Address', max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Support Phone Number', max_length=255, null=True)),
                ('chat', models.URLField(blank=True, help_text='URL to launch Support Chat', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
