# Generated by Django 5.0.2 on 2024-04-02 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_supportsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupportSettings',
        ),
    ]
