# Generated by Django 5.0.2 on 2024-03-24 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportindexpage',
            name='call_to_action',
        ),
        migrations.RemoveField(
            model_name='supportindexpage',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='supportpage',
            name='call_to_action',
        ),
        migrations.RemoveField(
            model_name='supportpage',
            name='heading',
        ),
    ]
