# Generated by Django 5.0.2 on 2024-04-02 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_delete_supportsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportindexpage',
            name='heading_intro',
        ),
        migrations.RemoveField(
            model_name='supportindexpage',
            name='heading_title',
        ),
    ]
