# Generated by Django 5.0.6 on 2024-07-20 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nearfieldcommunication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NearFieldCommunicationTag',
        ),
    ]
