# Generated by Django 5.0.6 on 2024-07-05 15:23

import django.db.models.deletion
import uuid
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nearfieldcommunication', '0001_initial'),
        ('notes', '0001_initial'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('body', wagtail.fields.RichTextField(blank=True, null=True, verbose_name='body')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('collection', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.collection')),
            ],
            options={
                'verbose_name': 'inventory',
                'verbose_name_plural': 'inventories',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('inventory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.inventory')),
            ],
            options={
                'verbose_name': 'inventory category',
                'verbose_name_plural': 'inventory catagories',
            },
            bases=('inventory.inventory',),
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('inventory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.inventory')),
            ],
            options={
                'verbose_name': 'inventory item',
                'verbose_name_plural': 'inventory items',
            },
            bases=('inventory.inventory',),
        ),
        migrations.CreateModel(
            name='InventoryLink',
            fields=[
                ('nearfieldcommunicationtag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nearfieldcommunication.nearfieldcommunicationtag')),
                ('inventory', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.inventory')),
            ],
            options={
                'verbose_name': 'inventory nfc mapping',
                'verbose_name_plural': 'inventory nfc mappings',
            },
            bases=('nearfieldcommunication.nearfieldcommunicationtag',),
        ),
        migrations.CreateModel(
            name='InventoryNote',
            fields=[
                ('note_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notes.note')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='inventory.inventory')),
            ],
            options={
                'verbose_name': 'inventory notes',
                'verbose_name_plural': 'inventory notes',
            },
            bases=('notes.note',),
        ),
    ]
