# Generated by Django 5.0.2 on 2024-07-03 21:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('inventory', '0001_initial'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
        ('wagtaildocs', '0012_uploadeddocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InventoryCollection',
            new_name='Inventory',
        ),
        migrations.RenameModel(
            old_name='InventoryCollectionLink',
            new_name='InventoryLink',
        ),
        migrations.RenameModel(
            old_name='InventoryCollectionNote',
            new_name='InventoryNote',
        ),
    ]
