# Generated by Django 5.0.6 on 2024-07-21 16:54

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(blank=True, verbose_name='Body')),
            ],
            options={
                'verbose_name': 'Inventory Index Page',
                'verbose_name_plural': 'Inventory Index Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='inventorypage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Body'),
        ),
    ]
