# Generated by Django 5.0.2 on 2024-06-06 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_digideximage_user_and_more'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalobjectjournalentry',
            name='caption',
        ),
        migrations.AlterField(
            model_name='digitalobjectjournalentry',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.digideximage'),
        ),
        migrations.AlterField(
            model_name='userprofilepage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.digideximage'),
        ),
    ]
