# Generated by Django 5.0.2 on 2024-05-27 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitization', '0003_remove_digitalobject_inventory'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_party',
            field=models.BooleanField(default=False, help_text='Indicates if this is the Party category.'),
        ),
        migrations.AlterField(
            model_name='category',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ItemizedDigit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemized_digits', to='inventory.category')),
                ('digit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_category', to='digitization.digitalobject')),
            ],
            options={
                'unique_together': {('category', 'digit')},
            },
        ),
    ]
