# Generated by Django 5.0.2 on 2024-04-24 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('nfc', '0002_alter_nearfieldcommunicationtag_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Digit',
            new_name='UserDigit',
        ),
    ]
