# Generated by Django 5.0.6 on 2024-07-20 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Asset',
            new_name='InventoryAsset',
        ),
        migrations.AlterModelOptions(
            name='inventorytag',
            options={'verbose_name': 'ntag', 'verbose_name_plural': 'ntags'},
        ),
        migrations.RenameModel(
            old_name='Inventory',
            new_name='InventoryPage',
        ),
        migrations.CreateModel(
            name='InventoryLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.inventorypage')),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='inventory.inventorytag')),
            ],
        ),
    ]
