# Generated by Django 5.0.2 on 2024-06-24 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorynote',
            name='page',
        ),
        migrations.RemoveField(
            model_name='categorynotegalleryimage',
            name='note',
        ),
        migrations.RemoveField(
            model_name='categorynotegalleryimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='categorypage',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='categorypage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='trainernearfieldcommunicationlink',
            name='page',
        ),
        migrations.RemoveField(
            model_name='trainernearfieldcommunicationlink',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='trainernote',
            name='page',
        ),
        migrations.RemoveField(
            model_name='trainernotegalleryimage',
            name='note',
        ),
        migrations.RemoveField(
            model_name='trainernotegalleryimage',
            name='image',
        ),
        migrations.DeleteModel(
            name='CategoryNearFieldCommunicationLink',
        ),
        migrations.DeleteModel(
            name='CategoryNote',
        ),
        migrations.DeleteModel(
            name='CategoryNoteGalleryImage',
        ),
        migrations.DeleteModel(
            name='CategoryPage',
        ),
        migrations.DeleteModel(
            name='TrainerNearFieldCommunicationLink',
        ),
        migrations.DeleteModel(
            name='TrainerNote',
        ),
        migrations.DeleteModel(
            name='TrainerNoteGalleryImage',
        ),
    ]
