# Generated by Django 5.0.2 on 2024-06-25 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorypage',
            options={'verbose_name': 'Inventory Category Page'},
        ),
    ]
