# Generated by Django 4.2.9 on 2024-02-11 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0023_remove_unit_taxonomy_un_complet_7de243_idx_and_more'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digit',
            name='journal_collection',
        ),
        migrations.AlterField(
            model_name='digit',
            name='taxonomic_unit',
            field=models.ForeignKey(blank=True, help_text='The taxonomic classification of the digitized plant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digits', to='taxonomy.unit'),
        ),
    ]
