# Generated by Django 5.0.2 on 2024-06-04 17:40

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_userprofilepage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilepage',
            name='introduction',
            field=wagtail.fields.RichTextField(blank=True, help_text='Short Biography about the user.', null=True),
        ),
    ]
