# Generated by Django 4.2.9 on 2024-02-22 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_digit_journal_collection_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='digit',
            old_name='taxonomic_unit',
            new_name='taxon',
        ),
        migrations.RemoveField(
            model_name='digit',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='digit',
            name='nfc_link',
        ),
    ]
