# Generated by Django 4.2.6 on 2024-02-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_digit_nfc_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='digit',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Indicates whether a public page is available for this digit.', verbose_name='Publicly Available'),
        ),
    ]
