# Generated by Django 5.0.6 on 2024-07-21 20:09

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryindexpage_inventorypage_body'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryindexpage',
            options={'verbose_name': 'inventory index'},
        ),
        migrations.AlterModelOptions(
            name='inventorypage',
            options={'verbose_name': 'inventory', 'verbose_name_plural': 'inventories'},
        ),
        migrations.AddField(
            model_name='inventoryindexpage',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.collection'),
        ),
        migrations.AlterField(
            model_name='inventoryindexpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='inventorypage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='body'),
        ),
    ]
