# Generated by Django 5.0.6 on 2024-07-30 20:39

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_userinventoryasset_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinventoryasset',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='body'),
        ),
    ]
