# Generated by Django 5.0.2 on 2024-05-31 19:25

import base.utils.storage
import django.db.models.deletion
import inventory.models.journal
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_category_unique_together_category_profile_and_more'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InventoryCategoryPage',
            new_name='CategoryPage',
        ),
        migrations.AlterUniqueTogether(
            name='inventorydigit',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='inventorydigit',
            name='category',
        ),
        migrations.RemoveField(
            model_name='inventorydigit',
            name='digit',
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('profile', 'name')},
        ),
        migrations.RenameModel(
            old_name='InventoryDigitPage',
            new_name='DigitalObjectPage',
        ),
        migrations.CreateModel(
            name='DigitalObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Digitized Object UUID')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True, verbose_name='Digitized Object Slug')),
                ('name', models.CharField(help_text='Digitized Object Name.', max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='Digitized Object Description.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemized_digits', to='inventory.category')),
            ],
        ),
        migrations.AlterField(
            model_name='digitalobjectpage',
            name='digit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='page', to='inventory.digitalobject'),
        ),
        migrations.CreateModel(
            name='EntryCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Journal Entry Collection UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('digital_object', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='journal', to='inventory.digitalobject')),
            ],
            options={
                'verbose_name': 'Journal Entry Collection',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, storage=base.utils.storage.PublicMediaStorage(), upload_to=inventory.models.journal.journal_image_path)),
                ('entry_number', models.PositiveIntegerField(default=1, help_text='Entry number in the journal.')),
                ('caption', models.CharField(blank=True, help_text='Image caption.', max_length=250, null=True)),
                ('note', models.TextField(blank=True, help_text='Journal entry note.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='inventory.entrycollection')),
            ],
        ),
    ]
