# Generated by Django 5.0.6 on 2024-07-27 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventoryasset_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryasset',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='inventory.inventorycategory', verbose_name='category'),
        ),
    ]
