# Generated by Django 5.0.2 on 2024-06-07 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_digitalobjectjournalentry_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalobjectjournalentry',
            name='entry_number',
            field=models.PositiveIntegerField(default=1, editable=False, verbose_name='Journal Entry Number'),
        ),
    ]
