# Generated by Django 5.0.2 on 2024-06-26 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventorypage_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorypage',
            name='name',
        ),
    ]
