# Generated by Django 5.0.2 on 2024-06-20 06:45

import django.db.models.deletion
import inventory.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0002_remove_digitalobjectpage_page_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NearFieldCommunicationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('serial_number', models.CharField(db_index=True, max_length=32, unique=True, validators=[inventory.validators.validate_ntag_serial])),
                ('ntag_type', models.CharField(choices=[('NTAG 213', 'NTAG 213'), ('NTAG 215', 'NTAG 215'), ('NTAG 216', 'NTAG 216')], default='NTAG 213', max_length=50)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'NTAG',
                'verbose_name_plural': 'NTAGs',
            },
        ),
        migrations.CreateModel(
            name='NearFieldCommunicationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(db_index=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('ntag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='inventory.nearfieldcommunicationtag')),
            ],
        ),
    ]
