# Generated by Django 5.0.6 on 2024-07-07 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_inventory_owner_inventory_collection_and_more'),
        ('nearfieldcommunication', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='InventoryCategory',
        ),
        migrations.RenameModel(
            old_name='Item',
            new_name='InventoryItem',
        ),
        migrations.RenameModel(
            old_name='Link',
            new_name='InventoryLink',
        ),
    ]
