# Generated by Django 5.0.2 on 2024-05-31 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_inventorycategorypage_categorypage_and_more'),
        ('nfc', '0002_remove_nearfieldcommunicationtag_digit_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryDigit',
        ),
        migrations.AlterUniqueTogether(
            name='digitalobject',
            unique_together={('category', 'name')},
        ),
    ]
