# Generated by Django 5.0.2 on 2024-06-04 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_userprofilepage_introduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinventorycategory',
            name='detail_page',
        ),
        migrations.RemoveField(
            model_name='userinventorycategory',
            name='page',
        ),
        migrations.DeleteModel(
            name='DigitalObjectCategory',
        ),
        migrations.DeleteModel(
            name='UserInventoryCategory',
        ),
    ]
