# Generated by Django 5.0.2 on 2024-07-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventorycategory_inventoryitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='inventory_ptr',
        ),
        migrations.AddField(
            model_name='inventory',
            name='type',
            field=models.CharField(choices=[('P', 'Profile'), ('C', 'Category'), ('I', 'Item')], default='I', max_length=1),
        ),
        migrations.DeleteModel(
            name='InventoryCategory',
        ),
        migrations.DeleteModel(
            name='InventoryItem',
        ),
    ]
