# Generated by Django 5.0.2 on 2024-05-28 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_itemizeddigitpage'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemizeddigitpage',
            name='digit',
        ),
        migrations.RemoveField(
            model_name='itemizeddigitpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.AddField(
            model_name='itemizeddigit',
            name='slug',
            field=models.SlugField(default='digit', editable=False, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='InventoryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('intro', models.TextField(blank=True)),
                ('digit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='page', to='inventory.itemizeddigit')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.DeleteModel(
            name='CategoryPage',
        ),
        migrations.DeleteModel(
            name='ItemizedDigitPage',
        ),
    ]
