# Generated by Django 5.0.2 on 2024-06-07 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_digitalobjectjournalentry_entry_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilepage',
            name='heading',
        ),
    ]
