# Generated by Django 5.0.6 on 2024-07-07 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inventory', '0003_rename_category_inventorycategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryViewRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restriction_type', models.CharField(choices=[('none', 'Public'), ('password', 'Private, accessible with a shared password'), ('login', 'Private, accessible to any logged-in users'), ('groups', 'Private, accessible to users in specific groups')], max_length=20)),
                ('password', models.CharField(blank=True, help_text='Shared passwords should not be used to protect sensitive content. Anyone who has this password will be able to view the content.', max_length=255, verbose_name='shared password')),
                ('groups', models.ManyToManyField(blank=True, to='auth.group', verbose_name='groups')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_restrictions', to='inventory.inventory', verbose_name='inventory')),
            ],
            options={
                'verbose_name': 'inventory view restriction',
                'verbose_name_plural': 'inventory view restrictions',
            },
        ),
    ]
