# Generated by Django 4.2.6 on 2024-01-26 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='digit',
            field=models.ForeignKey(help_text='The digitized plant to which this journal entry is related.', on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='inventory.digit'),
        ),
    ]
