# Generated by Django 5.0.6 on 2024-07-21 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventoryindexpage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryindexpage',
            options={'verbose_name': 'inventory page'},
        ),
    ]
