# Generated by Django 5.0.2 on 2024-06-27 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_inventorypage_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryNearFieldCommunicationLink',
        ),
    ]
