# Generated by Django 5.0.2 on 2024-06-01 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_digitalobject_user_entry_user_alter_userprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='digitalobject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemized_digits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entrycollection',
            name='digital_object',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journal', to='inventory.digitalobject'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
