# Generated by Django 5.0.2 on 2024-06-10 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_digideximage_user_and_more'),
        ('inventory', '0004_remove_userprofilepage_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycategorypage',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.digideximage'),
        ),
    ]
