# Generated by Django 5.0.6 on 2024-07-20 16:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_category_collection_remove_category_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='collection_ptr',
        ),
        migrations.RemoveField(
            model_name='item',
            name='owner',
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'Inventory Page', 'verbose_name_plural': 'Inventory Pages'},
        ),
        migrations.AddField(
            model_name='inventory',
            name='type',
            field=models.CharField(choices=[('asset', 'Asset'), ('group', 'Group')], default='group', max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='slug')),
                ('body', models.TextField(blank=True, null=True, verbose_name='body')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='inventory.inventory', verbose_name='inventory')),
            ],
            options={
                'verbose_name': 'asset',
                'verbose_name_plural': 'assets',
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
