# Generated by Django 4.2.9 on 2024-02-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_digit_ntag_alter_digit_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='digit',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Indicates if the digit should be publicly visible to the public or private. Digit is private by default.'),
        ),
    ]
