# Generated by Django 5.0.6 on 2024-08-01 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_userinventoryasset_inventoryassetpage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryindexpage',
            name='body',
        ),
        migrations.AddField(
            model_name='inventoryindexpage',
            name='intro',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
