# Generated by Django 5.0.2 on 2024-07-03 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_inventoryitem_inventory_ptr_inventory_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('inventory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.inventory')),
            ],
            options={
                'verbose_name': 'Inventory Category',
                'verbose_name_plural': 'Inventory Categories',
            },
            bases=('inventory.inventory',),
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('inventory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.inventory')),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
            },
            bases=('inventory.inventory',),
        ),
        migrations.CreateModel(
            name='InventoryProfile',
            fields=[
                ('inventory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.inventory')),
            ],
            options={
                'verbose_name': 'Inventory Profile',
                'verbose_name_plural': 'Inventory Profiles',
            },
            bases=('inventory.inventory',),
        ),
        migrations.AlterModelOptions(
            name='inventorylink',
            options={'verbose_name': 'Inventory NFC Mapping', 'verbose_name_plural': 'Inventory NFC Mappings'},
        ),
        migrations.AlterModelOptions(
            name='inventorynote',
            options={'verbose_name': 'Inventory Journal Entry', 'verbose_name_plural': 'Inventory Journal Entries'},
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='type',
        ),
        migrations.RemoveField(
            model_name='inventorynote',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='inventorynote',
            name='id',
        ),
        migrations.RemoveField(
            model_name='inventorynote',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='inventorynote',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='inventorynote',
            name='uuid',
        ),
        migrations.AddField(
            model_name='inventorynote',
            name='inventory_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.inventory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventorylink',
            name='inventory',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.inventory'),
        ),
    ]
