# Generated by Django 5.0.2 on 2024-06-01 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_category_user_alter_digitalobject_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='digitalobjectpage',
            old_name='digit',
            new_name='digital_object',
        ),
    ]
