# Generated by Django 5.0.6 on 2024-07-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventoryviewrestriction'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='_type',
            field=models.CharField(blank=True, choices=[('r', 'Root'), ('c', 'Category'), ('i', 'Item')], max_length=1, null=True, verbose_name='type'),
        ),
    ]
