# Generated by Django 5.0.2 on 2024-04-28 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_userindexpage_remove_profilepage_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digit',
            name='slug',
            field=models.SlugField(null=True, verbose_name='Digit Slug'),
        ),
        migrations.AddField(
            model_name='digit',
            name='user_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_digits', to='inventory.userpage'),
        ),
        migrations.AlterField(
            model_name='digit',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
