# Generated by Django 5.0.2 on 2024-05-28 23:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_itemizeddigit_uuid'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InventoryPage',
            new_name='ItemizedDigitPage',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='party', editable=False, max_length=255, unique=True, verbose_name='Inventory Category Slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemizeddigit',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, unique=True, verbose_name='Inventory Digit Slug'),
        ),
        migrations.AlterField(
            model_name='itemizeddigit',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Inventory Digit UUID'),
        ),
        migrations.CreateModel(
            name='InventoryCategoryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('intro', models.TextField(blank=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='page', to='inventory.category')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
