# Generated by Django 4.2.9 on 2024-02-26 18:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_digit_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='The unique identifier associated with the Digit.', unique=True, verbose_name='Digit UUID')),
                ('name', models.CharField(blank=True, help_text='A human-readable name for the digitized entity.', max_length=50, null=True)),
                ('description', models.TextField(blank=True, help_text='A short description of the digitized entity.', max_length=500, null=True)),
                ('is_public', models.BooleanField(default=False, help_text='Indicates if the digit should be publicly visible to the public or private. Digit is private by default.')),
                ('is_archived', models.BooleanField(default=False, help_text='Indicates whether the digit is archived.', verbose_name='Archived')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the digit instance was created.', verbose_name='Created At')),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='The date and time when the digit instance was last modified.', verbose_name='Last Modified')),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='The unique identifier associated with the Digit.', unique=True, verbose_name='Digit UUID')),
                ('name', models.CharField(blank=True, help_text='A human-readable name for the digitized entity.', max_length=50, null=True)),
                ('description', models.TextField(blank=True, help_text='A short description of the digitized entity.', max_length=500, null=True)),
                ('is_public', models.BooleanField(default=False, help_text='Indicates if the digit should be publicly visible to the public or private. Digit is private by default.')),
                ('is_archived', models.BooleanField(default=False, help_text='Indicates whether the digit is archived.', verbose_name='Archived')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the digit instance was created.', verbose_name='Created At')),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='The date and time when the digit instance was last modified.', verbose_name='Last Modified')),
                ('sunlight_requirement', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='digit',
            name='ntag',
        ),
        migrations.RemoveField(
            model_name='digit',
            name='taxon',
        ),
    ]
