# Generated by Django 5.0.2 on 2024-07-04 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventorycategory_inventoryitem_inventoryprofile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorynote',
            options={'verbose_name': 'Inventory Note', 'verbose_name_plural': 'Inventory Notes'},
        ),
    ]
