# Generated by Django 5.0.6 on 2024-07-18 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventorylink'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InventoryIndex',
            new_name='InventoryPage',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='InventoryCategory',
        ),
        migrations.DeleteModel(
            name='InventoryItem',
        ),
    ]
