# Generated by Django 5.0.6 on 2024-07-20 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_item_collection_ptr_remove_item_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='uuid',
        ),
    ]
