# Generated by Django 5.0.2 on 2024-06-28 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_inventorynoteimagegallery_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorypage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
