# Generated by Django 5.0.6 on 2024-07-20 21:56

import inventory.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_asset_slug_remove_inventory_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('serial_number', models.CharField(db_index=True, editable=False, max_length=32, unique=True, validators=[inventory.validators.validate_ntag_serial])),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'inventory tag',
                'verbose_name_plural': 'inventory tags',
            },
        ),
    ]
