# Generated by Django 5.0.6 on 2024-08-05 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_nearfieldcommunicationtag_inventorylink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorylink',
            name='url',
        ),
    ]
