# Generated by Django 4.2.9 on 2024-02-26 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_remove_collection_digit_collection_content_type_and_more'),
        ('link', '0006_ntag_ntag_use_alter_ntag_ntag_type'),
        ('inventory', '0006_pet_plant_remove_digit_ntag_remove_digit_taxon'),
        ('taxonomy', '0024_rename_short_author_author_cleaned_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Digit',
        ),
        migrations.AddField(
            model_name='plant',
            name='ntag',
            field=models.OneToOneField(blank=True, help_text='NTAG link for the digitized entity.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='link.ntag'),
        ),
        migrations.AddField(
            model_name='plant',
            name='taxon',
            field=models.ForeignKey(blank=True, help_text='The taxonomic classification of the digitized entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_digits', to='taxonomy.unit'),
        ),
        migrations.AddField(
            model_name='pet',
            name='ntag',
            field=models.OneToOneField(blank=True, help_text='NTAG link for the digitized entity.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='link.ntag'),
        ),
        migrations.AddField(
            model_name='pet',
            name='taxon',
            field=models.ForeignKey(blank=True, help_text='The taxonomic classification of the digitized entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_digits', to='taxonomy.unit'),
        ),
    ]
