# Generated by Django 5.0.6 on 2024-07-21 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventoryindexpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryIndexPage',
        ),
    ]
