# Generated by Django 5.0.2 on 2024-05-29 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_rename_inventorypage_itemizeddigitpage_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycategorypage',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inventorycategorypage',
            name='intro',
            field=models.TextField(blank=True, null=True),
        ),
    ]
