# Generated by Django 5.0.2 on 2024-05-29 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_inventorycategorypage_heading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemizeddigitpage',
            name='digit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='page', to='inventory.itemizeddigit'),
        ),
    ]
