# Generated by Django 5.0.6 on 2024-07-22 02:21

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_delete_inventoryindexpage'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseInventory',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(blank=True, null=True, verbose_name='body')),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.collection')),
            ],
            options={
                'verbose_name': 'inventory',
                'verbose_name_plural': 'inventories',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='inventorypage',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='inventorypage',
            name='page_ptr',
        ),
        migrations.AlterModelOptions(
            name='inventoryasset',
            options={'verbose_name': 'inventory asset', 'verbose_name_plural': 'inventory assets'},
        ),
        migrations.CreateModel(
            name='UserInventory',
            fields=[
                ('baseinventory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.baseinventory')),
                ('type', models.CharField(choices=[('file', 'File'), ('folder', 'Folder')], max_length=10)),
            ],
            options={
                'verbose_name': 'inventory page',
                'verbose_name_plural': 'inventorie pages',
            },
            bases=('inventory.baseinventory',),
        ),
        migrations.CreateModel(
            name='UserInventoryIndex',
            fields=[
                ('baseinventory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.baseinventory')),
            ],
            options={
                'verbose_name': 'user inventory index',
                'verbose_name_plural': 'user inventory indexes',
            },
            bases=('inventory.baseinventory',),
        ),
        migrations.AlterField(
            model_name='inventoryasset',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='inventory.userinventory', verbose_name='inventory'),
        ),
    ]
