# Generated by Django 4.2.9 on 2024-02-26 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0024_rename_short_author_author_cleaned_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0007_delete_digit_plant_ntag_plant_taxon_pet_ntag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='taxon',
            field=models.ForeignKey(blank=True, help_text='The taxonomic classification of the digitized entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='taxonomy.unit'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='taxon',
            field=models.ForeignKey(blank=True, help_text='The taxonomic classification of the digitized entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='taxonomy.unit'),
        ),
        migrations.CreateModel(
            name='Grouping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the group.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='The description of the group.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the grouping instance was created.', verbose_name='Created At')),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='The date and time when the grouping instance was last modified.', verbose_name='Last Modified')),
                ('user', models.ForeignKey(help_text='A relationship to the User model.', on_delete=django.db.models.deletion.CASCADE, related_name='digit_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.AddField(
            model_name='pet',
            name='grouping',
            field=models.ForeignKey(blank=True, help_text='The grouping this digit belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='inventory.grouping'),
        ),
        migrations.AddField(
            model_name='plant',
            name='grouping',
            field=models.ForeignKey(blank=True, help_text='The grouping this digit belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='inventory.grouping'),
        ),
    ]
