# Generated by Django 5.0.6 on 2024-07-22 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_baseinventory_remove_inventorypage_collection_and_more'),
        ('inventorytags', '0002_alter_inventorylink_inventory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryPage',
        ),
    ]
