# Generated by Django 5.0.6 on 2024-08-05 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_inventoryassetpage_last_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryassetpage',
            name='body',
        ),
    ]
