# Generated by Django 5.0.2 on 2024-05-31 01:29

import base.utils.storage
import django.db.models.deletion
import inventory.models.profile
import uuid
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitization', '0005_alter_digitalobject_user'),
        ('inventory', '0008_alter_itemizeddigitpage_digit'),
        ('journal', '0003_entry_entry_number'),
        ('nfc', '0002_alter_nearfieldcommunicationtag_digit'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RenameModel(
            old_name='ItemizedDigit',
            new_name='InventoryDigit',
        ),
        migrations.RenameModel(
            old_name='ItemizedDigitPage',
            new_name='InventoryDigitPage',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='User Profile UUID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='User Profile Slug')),
                ('image', models.ImageField(blank=True, null=True, storage=base.utils.storage.PublicMediaStorage(), upload_to=inventory.models.profile.user_avatar_path, verbose_name='User Profile Avatar')),
                ('bio', models.TextField(blank=True, help_text='Short Biography about the user.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
            },
        ),
        migrations.CreateModel(
            name='UserProfilePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='page', to='inventory.userprofile')),
            ],
            options={
                'verbose_name': 'User Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
