# Generated by Django 4.2.9 on 2024-02-27 01:11

import digidex.accounts.profile
import digidex.utils.custom_storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0008_alter_pet_taxon_alter_plant_taxon_grouping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouping',
            name='slug',
            field=models.SlugField(blank=True, help_text='The slug for the group.', max_length=255),
        ),
        migrations.AddField(
            model_name='pet',
            name='digit_type',
            field=models.CharField(choices=[('plant', 'Plant'), ('pet', 'Pet')], default='plant', help_text='The type of digitized entity, derived from NTAG use.', max_length=10),
        ),
        migrations.AddField(
            model_name='plant',
            name='digit_type',
            field=models.CharField(choices=[('plant', 'Plant'), ('pet', 'Pet')], default='plant', help_text='The type of digitized entity, derived from NTAG use.', max_length=10),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='A short biography of the user.', max_length=500)),
                ('location', models.CharField(blank=True, help_text='The location of the user.', max_length=30)),
                ('avatar', models.ImageField(blank=True, help_text='The avatar image of the profile.', null=True, storage=digidex.utils.custom_storage.PublicMediaStorage(), upload_to=digidex.accounts.profile.profile_avatar_directory_path)),
                ('is_public', models.BooleanField(default=False, help_text='Indicates if the profile should be publicly visible to the public or private. Profile is private by default.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the profile was created.', verbose_name='Created At')),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='The date and time when the profile was last modified.', verbose_name='Last Modified')),
                ('user', models.OneToOneField(help_text='The user associated with this profile.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
