# Generated by Django 5.0.6 on 2024-08-05 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_inventoryassetpage_body'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='inventorylink',
            name='inventory_i_asset_i_562e6f_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventorylink',
            name='inventory_i_tag_id_e09edc_idx',
        ),
        migrations.AlterField(
            model_name='inventorylink',
            name='asset',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_tag', to='inventory.inventoryassetpage'),
        ),
    ]
