# Generated by Django 4.2.9 on 2024-02-27 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_grouping_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='grouping',
            field=models.ForeignKey(help_text='The grouping this digit belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='inventory.grouping'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='grouping',
            field=models.ForeignKey(help_text='The grouping this digit belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='inventory.grouping'),
        ),
    ]
