# Generated by Django 5.0.2 on 2024-04-29 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_digitregistrationformpage_alter_userpage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitpage',
            name='digit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='page', to='inventory.digit'),
        ),
    ]
