# Generated by Django 5.0.2 on 2024-05-31 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_category_unique_together_category_user_profile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorycategorypage',
            options={'verbose_name': 'Inventory Category Page'},
        ),
        migrations.AlterModelOptions(
            name='userprofilepage',
            options={'verbose_name': 'User Profile Page'},
        ),
    ]
