# Generated by Django 5.0.6 on 2024-08-06 16:49

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_baseimage_caption'),
        ('inventory', '0010_remove_inventorylink_inventory_i_asset_i_562e6f_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetPageJournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('note', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.baseimage')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.baseimage')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='inventory.inventoryassetpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
