# Generated by Django 5.0.2 on 2024-04-29 22:57

import django.db.models.deletion
import modelcluster.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_digitpage_digit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digit',
            name='user',
        ),
        migrations.RemoveField(
            model_name='digitpage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='digitregistrationformpage',
            name='from_address',
        ),
        migrations.RemoveField(
            model_name='digitregistrationformpage',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='digitregistrationformpage',
            name='to_address',
        ),
        migrations.AddField(
            model_name='digit',
            name='user_page',
            field=modelcluster.fields.ParentalKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='digits', to='inventory.userpage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='digitpage',
            name='user_page',
            field=modelcluster.fields.ParentalKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='digit_pages', to='inventory.userpage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userpage',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='user_pages', to=settings.AUTH_USER_MODEL),
        ),
    ]
