# Generated by Django 4.2.9 on 2024-02-27 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_pet_grouping_alter_plant_grouping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='digit_type',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='digit_type',
        ),
    ]
