# Generated by Django 5.0.6 on 2024-07-25 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_userinventory_type_inventoryasset_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinventory',
            options={'verbose_name': 'inventory page', 'verbose_name_plural': 'inventory pages'},
        ),
    ]
