# Generated by Django 5.0.6 on 2024-08-06 20:52

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_remove_assetformpage_page_ptr_assetjournalentry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetjournalentry',
            name='note',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
