# Generated by Django 5.0.2 on 2024-05-01 20:15

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_delete_digit_delete_digitformfield_delete_digitpage_and_more'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDigitizedObjectIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, help_text='Introduction text to display at the top of the index page.')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='userdigitizedobject',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='userdigitizedobjectpage',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='userdigitizedobject',
            name='user_inventory',
            field=modelcluster.fields.ParentalKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='user_digits', to='inventory.userdigitizedobjectindexpage'),
            preserve_default=False,
        ),
    ]
