# Generated by Django 5.0.2 on 2024-05-01 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_userdigitizedobjectindexpage_and_more'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDigitizedObjectIndexPage',
            new_name='UserDigitizedObjectInventoryPage',
        ),
    ]
