# Generated by Django 5.0.6 on 2024-08-06 22:33

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_journalentry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='date',
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='inventory.inventoryassetpage'),
        ),
    ]
