# Generated by Django 5.0.6 on 2024-08-06 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_remove_journalentry_date_alter_journalentry_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryassetpage',
            name='taxon_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Taxonomy Identifier'),
        ),
    ]
