# Generated by Django 5.0.2 on 2024-05-03 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_remove_userdigitizedobject_user_inventory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdigitizedobject',
            old_name='page',
            new_name='parent',
        ),
        migrations.AlterField(
            model_name='userdigitizedobjectpage',
            name='user_digit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='detail_page', to='inventory.userdigitizedobject'),
        ),
    ]
