# Generated by Django 5.0.2 on 2024-05-03 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_rename_page_userdigitizedobject_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdigitizedobjectpagetag',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='userdigitizedobjectpagetag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='userdigitizedobjectpage',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='userdigitizedobjecttagindexpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='DigitizedObjectPageGalleryImage',
        ),
        migrations.DeleteModel(
            name='UserDigitizedObjectPageTag',
        ),
        migrations.DeleteModel(
            name='UserDigitizedObjectTagIndexPage',
        ),
    ]
