# Generated by Django 5.0.2 on 2024-05-04 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_remove_userdigitizedobjectpagetag_content_object_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdigitizedobject',
            name='parent',
        ),
        migrations.AddField(
            model_name='userdigitizedobject',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_digits', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
