# Generated by Django 5.0.2 on 2024-05-04 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitization', '0003_alter_digitizedobject_description_and_more'),
        ('inventory', '0020_remove_userdigitizedobject_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdigitizedobject',
            options={},
        ),
        migrations.RemoveField(
            model_name='userdigitizedobject',
            name='sort_order',
        ),
        migrations.AlterField(
            model_name='userdigitizedobject',
            name='digit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_association', to='digitization.digitizedobject'),
        ),
        migrations.AlterField(
            model_name='userdigitizedobject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_digits', to=settings.AUTH_USER_MODEL),
        ),
    ]
