# Generated by Django 5.0.6 on 2024-08-08 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_rename_trainerpage_trainerindexpage'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='slug',
        ),
        migrations.CreateModel(
            name='TrainerIndexCollection',
            fields=[
                ('collection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.collection')),
                ('trainer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection', to='inventory.trainer')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.collection',),
        ),
    ]
