# Generated by Django 5.0.6 on 2024-08-08 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_remove_trainer_collection_remove_trainer_slug_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainerIndexCollection',
        ),
    ]
