# Generated by Django 5.0.2 on 2024-05-09 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_userdigitizedobjectinventorypage_heading'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdigitizedobject',
            name='user',
        ),
        migrations.AddField(
            model_name='userdigitizedobject',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_digits', to='profiles.userprofile'),
            preserve_default=False,
        ),
    ]
