# Generated by Django 5.0.6 on 2024-08-08 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_delete_trainerindexcollection'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerIndexCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.collection')),
                ('trainer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection', to='inventory.trainer')),
            ],
        ),
    ]
