# Generated by Django 5.0.2 on 2024-05-10 16:22

import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields
import uuid
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_remove_userdigitizedobject_user_and_more'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdigitizedobject',
            options={'ordering': ['sort_order']},
        ),
        migrations.RemoveField(
            model_name='userdigitizedobject',
            name='digit',
        ),
        migrations.RemoveField(
            model_name='userdigitizedobjectpage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userdigitizedobjectpage',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='userdigitizedobjectpage',
            name='user_digit',
        ),
        migrations.AddField(
            model_name='userdigitizedobject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdigitizedobject',
            name='description',
            field=models.TextField(blank=True, help_text='Digitized object description.', null=True),
        ),
        migrations.AddField(
            model_name='userdigitizedobject',
            name='detail_page',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='detailed_digit', to='inventory.userdigitizedobjectpage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdigitizedobject',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userdigitizedobject',
            name='name',
            field=models.CharField(help_text='Digitized object name.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdigitizedobject',
            name='page',
            field=modelcluster.fields.ParentalKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_digitized_objects', to='inventory.userdigitizedobjectinventorypage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdigitizedobject',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='userdigitizedobject',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Digitized Object UUID'),
        ),
        migrations.AddField(
            model_name='userdigitizedobjectpage',
            name='heading',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userdigitizedobjectpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.CreateModel(
            name='UserDigitizedObjectNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, help_text='Image caption.', max_length=250, null=True)),
                ('digit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='inventory.userdigitizedobject')),
                ('image', models.ForeignKey(help_text='Digitized object image.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='digit_notes', to='inventory.userdigitizedobjectpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
