# Generated by Django 5.0.6 on 2024-08-08 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_trainerindexcollection'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerindexpage',
            name='collection',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.collection'),
        ),
        migrations.DeleteModel(
            name='TrainerIndexCollection',
        ),
    ]
