# Generated by Django 5.0.2 on 2024-05-15 15:05

import django.db.models.deletion
import modelcluster.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_alter_userdigitizedobject_options_and_more'),
        ('profiles', '0002_alter_userprofile_avatar'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Digitized Object UUID')),
                ('name', models.CharField(default='Inventory', help_text='Digitized Object Inventory name.', max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Digitized Object Inventory Slug')),
                ('profile_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='profiles.userprofilepage')),
            ],
        ),
        migrations.CreateModel(
            name='UserInventoryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('intro', models.TextField(blank=True, help_text='Introduction text to display at the top of the index page.')),
                ('inventory', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_page', to='inventory.userinventory')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='userinventory',
            name='detail_page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='detailed_digit', to='inventory.userinventorypage'),
        ),
        migrations.AlterField(
            model_name='userdigitizedobject',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_digitized_objects', to='inventory.userinventorypage'),
        ),
        migrations.AlterUniqueTogether(
            name='userinventory',
            unique_together={('profile_page', 'slug')},
        ),
        migrations.DeleteModel(
            name='UserDigitizedObjectInventoryPage',
        ),
    ]
