# Generated by Django 5.0.6 on 2024-08-08 03:48

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_trainerindexpage_collection_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerindexpage',
            name='trainer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainerindexpage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Trainer',
        ),
    ]
