# Generated by Django 5.0.2 on 2024-05-18 21:22

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_userinventory_userinventorypage_and_more'),
        ('nfc', '0020_rename_digitized_object_nearfieldcommunicationtag_digit'),
        ('profiles', '0002_alter_userprofile_avatar'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDigitizedObject',
            new_name='UserDigit',
        ),
        migrations.RenameModel(
            old_name='UserDigitizedObjectPage',
            new_name='UserDigitPage',
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, help_text='Image caption.', max_length=250, null=True)),
                ('digit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='inventory.userdigit')),
                ('image', models.ForeignKey(help_text='Digitized object image.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='digit_journal_entries', to='inventory.userdigitpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='UserDigitizedObjectNote',
        ),
    ]
