# Generated by Django 5.0.6 on 2024-08-08 04:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_alter_trainerindexpage_trainer_and_more'),
        ('wagtailcore', '0093_uploadedfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInventoryPage',
            new_name='TrainerInventoryPage',
        ),
        migrations.DeleteModel(
            name='TrainerIndexPage',
        ),
    ]
