# Generated by Django 5.0.6 on 2024-08-08 04:20

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_rename_trainerindexpage_trainerinventorypage_and_more'),
        ('wagtailcore', '0093_uploadedfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainerinventorypage',
            options={'verbose_name': 'trainer page', 'verbose_name_plural': 'trainer pages'},
        ),
        migrations.RemoveField(
            model_name='trainerinventorypage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='trainerinventorypage',
            name='uuid',
        ),
        migrations.AddField(
            model_name='trainerinventorypage',
            name='trainer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trainerinventorypage',
            name='collection',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.collection'),
        ),
        migrations.AlterField(
            model_name='trainerinventorypage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
