# Generated by Django 5.0.2 on 2024-05-18 21:26

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_rename_userdigitizedobject_userdigit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdigit',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemized_digits', to='inventory.userinventorypage'),
        ),
    ]
