# Generated by Django 5.0.6 on 2024-08-08 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_alter_trainerinventorypage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainerinventorypage',
            name='description',
        ),
    ]
