# Generated by Django 5.0.2 on 2024-05-19 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_alter_userinventory_unique_together_and_more'),
        ('nfc', '0021_alter_nearfieldcommunicationtag_digit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdigit',
            name='detail_page',
        ),
        migrations.RemoveField(
            model_name='userdigit',
            name='page',
        ),
        migrations.RemoveField(
            model_name='userdigit',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='userdigitpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='JournalEntry',
        ),
        migrations.DeleteModel(
            name='UserDigit',
        ),
        migrations.DeleteModel(
            name='UserDigitPage',
        ),
    ]
