# Generated by Django 5.0.6 on 2024-08-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_nearfieldcommunicationtag_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearfieldcommunicationtag',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
