# Generated by Django 5.0.2 on 2024-05-24 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_userinventory_created_at_userinventory_last_modified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userinventory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='userinventory',
            unique_together={('user', 'name')},
        ),
        migrations.RemoveField(
            model_name='userinventory',
            name='detail_page',
        ),
        migrations.RemoveField(
            model_name='userinventory',
            name='profile_page',
        ),
        migrations.RemoveField(
            model_name='userinventory',
            name='sort_order',
        ),
    ]
