# Generated by Django 5.0.2 on 2024-05-24 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_alter_userinventory_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinventory',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userinventorypage',
            name='inventory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='page', to='inventory.userinventory'),
        ),
    ]
