# Generated by Django 5.0.6 on 2024-08-09 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_nearfieldcommunicationtagtype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NearFieldCommunicationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_tag', to='inventory.inventoryassetpage')),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='inventory.nearfieldcommunicationtag')),
            ],
            options={
                'verbose_name': 'near field communication link',
                'verbose_name_plural': 'near field communication links',
            },
        ),
        migrations.DeleteModel(
            name='NearFieldCommunicationRecord',
        ),
    ]
