# Generated by Django 5.0.6 on 2024-08-09 03:15

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_nearfieldcommunicationlink_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NearFieldCommunicationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('asset', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_tag', to='inventory.inventoryassetpage')),
                ('tag', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='inventory.nearfieldcommunicationtag')),
            ],
            options={
                'verbose_name': 'near field communication record',
                'verbose_name_plural': 'near field communication records',
            },
        ),
        migrations.DeleteModel(
            name='NearFieldCommunicationLink',
        ),
    ]
