# Generated by Django 5.0.2 on 2024-05-27 15:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_alter_userinventory_user_and_more'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinventorypage',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='userinventorypage',
            name='page_ptr',
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Inventory Category UUID')),
                ('name', models.CharField(default='Category', help_text='Inventory Category Name.', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Inventory Category description.', null=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Inventory Category Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='category', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CategoryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('intro', models.TextField(blank=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='page', to='inventory.category')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.DeleteModel(
            name='UserInventory',
        ),
        migrations.DeleteModel(
            name='UserInventoryPage',
        ),
    ]
