# Generated by Django 4.2.9 on 2024-02-08 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('email_verification', 'Email Verification'), ('password_reset', 'Password Reset'), ('contact_us', 'Contact Us Form')], help_text='The reason why the email was sent.', max_length=100)),
                ('to_email', models.EmailField(help_text='The email address the email was sent to.', max_length=255)),
                ('from_email', models.EmailField(help_text='The email address the email was sent from.', max_length=255)),
                ('subject', models.CharField(help_text='Subject of the email.', max_length=255)),
                ('body', models.TextField(help_text='Text content of the email.')),
                ('html_content', models.TextField(blank=True, help_text='HTML content of the email.', null=True)),
                ('status', models.CharField(default='sent', help_text='Status of the email (sent, failed, etc.)', max_length=50)),
                ('date_sent', models.DateTimeField(auto_now_add=True, help_text='Date and time the email was sent.')),
                ('user', models.ForeignKey(blank=True, help_text='The user associated with this email, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-date_sent'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_active', models.DateTimeField(auto_now_add=True, help_text='The date and time when the activity was recorded.')),
                ('user', models.ForeignKey(help_text='Reference to the user who performed the activity.', on_delete=django.db.models.deletion.CASCADE, related_name='recent_activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
