# Generated by Django 4.2.6 on 2024-01-11 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0001_initial'),
        ('nfc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Digit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='A human-readable name for the digitized plant.', max_length=50, null=True)),
                ('description', models.TextField(blank=True, help_text='A short description of the digitized plant.', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the digit instance was created.', verbose_name='Created At')),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='The date and time when the digit instance was last modified.', verbose_name='Last Modified')),
                ('nfc_link', models.OneToOneField(help_text='NFC link for the digitized plant.', on_delete=django.db.models.deletion.CASCADE, related_name='digit', to='nfc.link')),
                ('taxonomic_unit', models.ForeignKey(blank=True, help_text='The taxonomic classification of the digitized plant.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='digits', to='taxonomy.unit')),
            ],
            options={
                'verbose_name': 'Digit',
                'verbose_name_plural': 'Digits',
            },
        ),
    ]
