# Generated by Django 4.2.6 on 2024-01-04 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfc', '0003_remove_link_counter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_digit_created_at_digit_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='digit',
            name='nfc_link',
            field=models.OneToOneField(blank=True, help_text='NFC link for the digitized plant.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='digit', to='nfc.link'),
        ),
        migrations.AddField(
            model_name='digit',
            name='user',
            field=models.ForeignKey(default=1, help_text='The owner of the digitized plant.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Journal',
        ),
    ]
