# Generated by Django 4.2.6 on 2023-11-25 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_alter_group_options_alter_group_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='created_by',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='group',
            name='user',
            field=models.ForeignKey(default=7, help_text='The user who created the group.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('name', 'user')},
        ),
    ]
