# Generated by Django 4.2.6 on 2023-11-27 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0003_rename_created_by_link_user_alter_group_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name'], 'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.RemoveField(
            model_name='link',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='link',
            name='group',
        ),
        migrations.RemoveField(
            model_name='link',
            name='user',
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(help_text='The unique name identifying the group.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='user',
            field=models.ForeignKey(help_text='The user who created and owns the group.', on_delete=django.db.models.deletion.CASCADE, related_name='groupings', to=settings.AUTH_USER_MODEL),
        ),
    ]
