# Generated by Django 4.2.6 on 2024-01-04 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0003_digit_nfc_link_digit_user_delete_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digit',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The owner of the digitized plant.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
