# Generated by Django 4.2.6 on 2023-11-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_group_options_remove_link_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='secret',
        ),
        migrations.AlterField(
            model_name='link',
            name='active',
            field=models.BooleanField(default=False, help_text='Indicates whether the link is currently active and mapped to a digital object.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='link',
            name='secret_hash',
            field=models.CharField(editable=False, help_text='The hash of a secret key for secure identification and access.', max_length=64, verbose_name='Secret Hash'),
        ),
        migrations.AlterField(
            model_name='link',
            name='serial_number',
            field=models.CharField(help_text='The unique serial number associated with the NFC tag or identification mechanism.', max_length=255, unique=True, verbose_name='Tag Serial Number'),
        ),
    ]
