# Generated by Django 4.2.6 on 2024-01-05 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfc', '0004_link_counter_link_user'),
        ('inventory', '0004_alter_digit_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digit',
            name='user',
        ),
        migrations.AlterField(
            model_name='digit',
            name='nfc_link',
            field=models.OneToOneField(default=1, help_text='NFC link for the digitized plant.', on_delete=django.db.models.deletion.CASCADE, related_name='digit', to='nfc.link'),
            preserve_default=False,
        ),
    ]
