# Generated by Django 4.2.6 on 2023-12-03 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_link_secret_alter_link_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='secret_hash',
        ),
    ]
