# Generated by Django 4.2.6 on 2023-12-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_link_secret_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='serial_number',
            field=models.CharField(db_index=True, help_text='The unique serial number associated with the NFC tag or identification mechanism.', max_length=255, unique=True, verbose_name='Tag Serial Number'),
        ),
    ]
