# Generated by Django 4.2.6 on 2023-12-09 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_digit_group_remove_digit_link_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0007_alter_link_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='digit',
            field=models.OneToOneField(blank=True, help_text='The digitized plant associated with this NFC tag.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link', to='core.digit'),
        ),
        migrations.AddField(
            model_name='link',
            name='group',
            field=models.ForeignKey(blank=True, help_text='The group to which this link belongs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='inventory.group'),
        ),
        migrations.AddField(
            model_name='link',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user who created and owns the link.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to=settings.AUTH_USER_MODEL),
        ),
    ]
