# Generated by Django 4.2.6 on 2023-12-09 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_link_digit_link_group_link_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='group',
            field=models.ForeignKey(blank=True, help_text='The group this link is associated with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='inventory.group'),
        ),
    ]
