# Generated by Django 4.2.6 on 2024-01-01 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_link_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='group',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
