# Generated by Django 5.0.2 on 2024-04-24 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_userprofilepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofilepage',
            name='user',
            field=models.OneToOneField(help_text='The user associated with this profile.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_page', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
