# Generated by Django 5.0.2 on 2024-05-27 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userindexpage_userpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpage',
            name='user',
        ),
    ]
