# Generated by Django 4.2.6 on 2024-02-01 22:09

import digidex.accounts.models.profile
import digidex.utils.custom_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='The avatar image of the profile.', null=True, storage=digidex.utils.custom_storage.PublicMediaStorage(), upload_to=digidex.accounts.models.profile.profile_avatar_directory_path),
        ),
    ]
