# Generated by Django 4.2.9 on 2024-02-22 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_is_public_user_username_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Indicates if the profile should be publicly visible to the public or private. Profile is private by default.'),
        ),
    ]
