# Generated by Django 4.2.9 on 2024-02-05 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={},
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='timestamp',
            new_name='last_active',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='activity_status',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='content',
        ),
    ]
