# Generated by Django 5.0.2 on 2024-05-31 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_avatar_userprofile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='slug',
        ),
        migrations.DeleteModel(
            name='UserIndexPage',
        ),
        migrations.DeleteModel(
            name='UserPage',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
