# Generated by Django 4.2.9 on 2024-02-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Required. 32 characters or fewer. Letters, digits and .(periods) only.', max_length=32, unique=True),
        ),
    ]
