# Generated by Django 5.0.2 on 2024-04-25 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_userprofilepage_profilepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(help_text="Used for it's SEO-friendly properties on the front-end.", unique=True, verbose_name='Username Slug'),
        ),
    ]
