# Generated by Django 4.2.9 on 2024-02-24 16:37

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Required. 32 characters or fewer. Letters, digits and dashes only.', max_length=32, unique=True, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['ASCII'], message='Username must contain only letters, digits, and dashes.', regex='^[\\w-]+$')]),
        ),
    ]
