# Generated by Django 5.0.2 on 2024-04-02 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_loginpage_signuppage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountindexpage',
            name='heading_intro',
        ),
        migrations.RemoveField(
            model_name='accountindexpage',
            name='heading_title',
        ),
        migrations.RemoveField(
            model_name='loginpage',
            name='heading_intro',
        ),
        migrations.RemoveField(
            model_name='loginpage',
            name='heading_title',
        ),
        migrations.RemoveField(
            model_name='signuppage',
            name='heading_intro',
        ),
        migrations.RemoveField(
            model_name='signuppage',
            name='heading_title',
        ),
    ]
