# Generated by Django 5.0.2 on 2024-05-31 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_userpage_page_ptr_remove_userprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(default='slug', max_length=255, unique=True, verbose_name='User Slug'),
            preserve_default=False,
        ),
    ]
