# Generated by Django 5.0.2 on 2024-04-27 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepage',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='profilepage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='profilepage',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProfileIndexPage',
        ),
        migrations.DeleteModel(
            name='ProfilePage',
        ),
    ]
