# Generated by Django 4.2.9 on 2024-02-27 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username_slug',
            new_name='slug',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
