# Generated by Django 5.0.2 on 2024-04-28 22:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_profilepage_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Username Slug'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True, verbose_name='User UUID'),
        ),
    ]
