# Generated by Django 5.0.2 on 2024-05-01 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='biography',
        ),
    ]
