# Generated by Django 5.0.2 on 2024-05-01 04:18

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_userprofile_biography'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileindexpage',
            old_name='body',
            new_name='intro',
        ),
        migrations.AddField(
            model_name='userprofileindexpage',
            name='heading',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofilepage',
            name='heading',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofilepage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
