# Generated by Django 5.0.2 on 2024-05-01 16:56

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_body_userprofileindexpage_intro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilepage',
            name='body',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=wagtail.fields.RichTextField(blank=True, help_text='Short Biography about the user.'),
        ),
    ]
