# Generated by Django 5.0.2 on 2024-05-01 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_userprofilepage_body_userprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilepage',
            name='profile',
            field=models.OneToOneField(help_text='Link to the associated user profile.', on_delete=django.db.models.deletion.PROTECT, related_name='profile_page', to='accounts.userprofile'),
        ),
    ]
