# Generated by Django 5.0.2 on 2024-05-07 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_usercollection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileIndexPage',
        ),
    ]
