# Generated by Django 5.0.2 on 2024-05-08 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_delete_userprofileindexpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofilepage',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='userprofilepage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='UserCollection',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='UserProfilePage',
        ),
    ]
