# Generated by Django 5.0.2 on 2024-06-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_alter_trainerpage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainernote',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='trainerpage',
            options={'verbose_name': 'User Trainer Page'},
        ),
        migrations.AddField(
            model_name='trainernote',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
