# Generated by Django 5.0.2 on 2024-06-27 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0004_delete_trainernearfieldcommunicationlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainernoteimagegallery',
            name='note',
        ),
        migrations.RemoveField(
            model_name='trainernoteimagegallery',
            name='noteimagegallery_ptr',
        ),
        migrations.DeleteModel(
            name='TrainerNote',
        ),
        migrations.DeleteModel(
            name='TrainerNoteImageGallery',
        ),
    ]
