# Generated by Django 5.0.2 on 2024-06-27 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0005_remove_trainernoteimagegallery_note_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainerpage',
            options={'verbose_name': 'Trainer Profile Page'},
        ),
    ]
