# Generated by Django 5.0.2 on 2024-06-28 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0006_alter_trainerpage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerpage',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
