from .blog_page import BlogView
from .checkout_page import CheckoutView
from .company_page import CompanyView
from .contact_page import ContactView
from .detail_category import DetailCategoryView
from .detail_post import DetailPostView
from .detail_product import DetailProductView
from .detail_sku import DetailSKUView
from .landing_page import LandingView
from .order_confirmation import OrderConfirmationView
from .paypal_checkout import PayPalCheckoutView
from .pricing_page import PricingView
from .solutions_page import SolutionsView
from .thank_you_page import ThankYouView
