# Generated by Django 5.0.2 on 2024-03-22 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorizationIndexPage',
        ),
    ]
