# Generated by Django 5.0.2 on 2024-03-22 04:15

import base.fields.django_fields
import digidex.utils.storage
import django.db.models.deletion
import persona.models
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='digidexprofile',
            name='avatar',
            field=base.fields.django_fields.BaseImageField(blank=True, help_text='The avatar image of the profile.', null=True, storage=digidex.utils.storage.PublicMediaStorage, upload_to=persona.models.profile_avatar_directory_path),
        ),
        migrations.AlterField(
            model_name='digidexprofile',
            name='bio',
            field=base.fields.django_fields.BaseTextField(blank=True, help_text='A short biography of the user.', max_length=500),
        ),
        migrations.AlterField(
            model_name='digidexprofile',
            name='created_at',
            field=base.fields.django_fields.BaseDateTimeField(auto_now_add=True, help_text='The date and time when the profile was created.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='digidexprofile',
            name='is_public',
            field=base.fields.django_fields.BaseBooleanField(default=False, help_text='Indicates if the profile should be publicly visible to the public or private. Profile is private by default.'),
        ),
        migrations.AlterField(
            model_name='digidexprofile',
            name='last_modified',
            field=base.fields.django_fields.BaseDateTimeField(auto_now=True, help_text='The date and time when the profile was last modified.', verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='digidexprofile',
            name='location',
            field=base.fields.django_fields.BaseCharField(blank=True, help_text='The location of the user.', max_length=30),
        ),
        migrations.AlterField(
            model_name='digidexprofile',
            name='slug',
            field=base.fields.django_fields.BaseSlugField(editable=False, help_text='Slugified version of the username for URL usage.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='digidexprofile',
            name='user',
            field=base.fields.django_fields.BaseOneToOneField(help_text='The user associated with this profile.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
