# Generated by Django 5.0.2 on 2024-03-24 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_remove_personaindexpage_introduction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaindexpage',
            name='call_to_action',
        ),
        migrations.RemoveField(
            model_name='personaindexpage',
            name='heading',
        ),
    ]
