# Generated by Django 4.1.7 on 2023-05-21 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_greenhouse_greenhousesection_growthchamber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greenhousesection',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='greenhousesection',
            name='greenhouse',
        ),
        migrations.RemoveField(
            model_name='greenhousesection',
            name='user',
        ),
        migrations.RemoveField(
            model_name='growthchamber',
            name='air_speed_sensor',
        ),
        migrations.RemoveField(
            model_name='growthchamber',
            name='humidity_sensor',
        ),
        migrations.RemoveField(
            model_name='growthchamber',
            name='light_sensor',
        ),
        migrations.RemoveField(
            model_name='growthchamber',
            name='ndir_co2_sensor',
        ),
        migrations.RemoveField(
            model_name='growthchamber',
            name='temperature_sensor',
        ),
        migrations.RemoveField(
            model_name='growthchamber',
            name='voc_sensor',
        ),
        migrations.DeleteModel(
            name='Greenhouse',
        ),
        migrations.DeleteModel(
            name='GreenhouseSection',
        ),
    ]
