# Generated by Django 5.0.2 on 2024-04-02 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryindexpage',
            name='heading_intro',
        ),
        migrations.RemoveField(
            model_name='categoryindexpage',
            name='heading_title',
        ),
        migrations.RemoveField(
            model_name='categorypage',
            name='heading_intro',
        ),
        migrations.RemoveField(
            model_name='categorypage',
            name='heading_title',
        ),
    ]
