# Generated by Django 5.0.6 on 2024-07-20 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryLink',
        ),
    ]
