# Generated by Django 4.2.6 on 2024-01-29 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfc',
            name='uuid',
        ),
    ]
