# Generated by Django 4.2.9 on 2024-02-06 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nfc',
            options={'verbose_name': 'NFC Tag', 'verbose_name_plural': 'NFC Tags'},
        ),
    ]
