# Generated by Django 4.2.9 on 2024-02-11 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('link', '0002_alter_nfc_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfc',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user associated with this link.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
