# Generated by Django 4.2.9 on 2024-02-22 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_taxonomic_unit_digit_taxon_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('link', '0003_alter_nfc_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='NTAG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(db_index=True, help_text='The unique serial number associated with the NFC tag.', max_length=32, unique=True, verbose_name='Tag Serial Number')),
                ('manufacturer', models.CharField(blank=True, db_column='manufacturer_id', help_text='The manufacturer of the NFC tag.', max_length=2, verbose_name='Manufacturer')),
                ('version', models.CharField(blank=True, help_text='The version of the NFC tag.', max_length=4, verbose_name='Version')),
                ('counter', models.PositiveIntegerField(default=0, help_text='The counter value associated with the NFC tag.', verbose_name='Counter')),
                ('active', models.BooleanField(default=False, help_text='Indicates whether the link is currently active and mapped to a digital object.', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the link instance was created.', verbose_name='Created At')),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='The date and time when the link instance was last modified.', verbose_name='Last Modified')),
                ('ntag_type', models.CharField(blank=True, choices=[(213, 'NTAG213'), (215, 'NTAG215'), (216, 'NTAG216')], help_text='The type of the NTAG.', max_length=8, verbose_name='NTAG Type')),
                ('user', models.ForeignKey(blank=True, help_text='The user associated with this link.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'NTAG',
                'verbose_name_plural': 'NTAGs',
            },
        ),
        migrations.DeleteModel(
            name='NFC',
        ),
    ]
