# Generated by Django 4.2.9 on 2024-02-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0004_ntag_delete_nfc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ntag',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='ntag',
            name='version',
        ),
        migrations.AddField(
            model_name='ntag',
            name='eeprom',
            field=models.BinaryField(blank=True, help_text='The EEPROM data associated with the NFC tag.', null=True, verbose_name='EEPROM'),
        ),
    ]
