# Generated by Django 4.2.9 on 2024-02-27 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0006_ntag_ntag_use_alter_ntag_ntag_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ntag',
            old_name='ntag_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='ntag',
            old_name='ntag_use',
            new_name='use',
        ),
    ]
