# Generated by Django 4.2.9 on 2024-02-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0007_rename_ntag_type_ntag_type_rename_ntag_use_ntag_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='ntag',
            name='slug',
            field=models.SlugField(blank=True, help_text='The slug for the NFC object.', max_length=255),
        ),
        migrations.AlterField(
            model_name='ntag',
            name='use',
            field=models.CharField(choices=[('plant_label', 'Plant Label'), ('dog_tag', 'Dog Tag'), ('cat_tag', 'Cat Tag')], default='plant_label', help_text='The intended use of the NTAG.', max_length=20, verbose_name='NTAG Use'),
        ),
    ]
