# Generated by Django 4.2.9 on 2024-02-29 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0008_ntag_slug_alter_ntag_use'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ntag',
            name='slug',
        ),
    ]
