# Generated by Django 5.0.2 on 2024-03-22 04:15

import base.fields.django_fields
import django.core.validators
import re
import uuid
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digidexuser',
            name='email_confirmed',
            field=base.fields.django_fields.BaseBooleanField(default=False, help_text='Indicates whether the user has confirmed their email address.'),
        ),
        migrations.AlterField(
            model_name='digidexuser',
            name='username',
            field=base.fields.django_fields.BaseCharField(help_text='Required. 32 characters or fewer. Letters, digits and dashes only.', max_length=32, unique=True, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['ASCII'], message='Username must contain only letters, digits, and dashes.', regex='^[\\w-]+$')]),
        ),
        migrations.AlterField(
            model_name='digidexuser',
            name='uuid',
            field=base.fields.django_fields.BaseUUIDField(db_index=True, default=uuid.uuid4, help_text='The universal unique identifier associated with each User.', unique=True, verbose_name='User UUID'),
        ),
    ]
