# Generated by Django 5.0.2 on 2024-05-20 02:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0005_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Digitized Object UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('profile_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='party', to='profiles.userprofilepage')),
            ],
        ),
    ]
