# Generated by Django 5.0.2 on 2024-05-23 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
        ('profiles', '0005_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userparty',
            name='profile_page',
        ),
        migrations.AddField(
            model_name='userparty',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='party', to='profiles.userprofile'),
            preserve_default=False,
        ),
    ]
