# Generated by Django 5.0.2 on 2024-05-24 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_remove_userparty_profile_page_userparty_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userparty',
            name='profile',
        ),
        migrations.AddField(
            model_name='userparty',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='party', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
