# Generated by Django 5.0.2 on 2024-03-07 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_companypage_contactpage_landingpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='CompanyPage',
        ),
        migrations.DeleteModel(
            name='ContactPage',
        ),
    ]
