# Generated by Django 5.0.2 on 2024-03-21 04:43

import base.blocks.basic_blocks
import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage_hero_cta_homepage_hero_cta_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='hero_cta',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_cta_link',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='image',
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_content',
            field=wagtail.fields.StreamField([('hero_section', wagtail.blocks.StructBlock([('content', wagtail.blocks.StructBlock([('content_block', wagtail.blocks.StreamBlock([('grid', wagtail.blocks.StreamBlock([('items', wagtail.blocks.StreamBlock([('base_block', wagtail.blocks.StructBlock([]))], min_num=1))])), ('block', wagtail.blocks.StructBlock([]))], max_num=1))])), ('hero_block', wagtail.blocks.StructBlock([('headline', base.blocks.basic_blocks.BaseCharBlock(help_text='Enter the headline for the value proposition. Capped at 75 characters to enforce conciseness.', max_length=75, required=True)), ('subheadline', base.blocks.basic_blocks.BaseCharBlock(help_text='Enter the subheadline for the value proposition. Capped at 150 characters to enforce brevity.', max_length=150, required=False)), ('cta', wagtail.blocks.StructBlock([('text', base.blocks.basic_blocks.BaseCharBlock(help_text='Enter the text for the call to action.', max_length=75, required=True)), ('url', base.blocks.basic_blocks.BaseURLBlock(help_text='Enter the url for the call to action.', required=True))]))])), ('hero_lottie', wagtail.blocks.StructBlock([('lottie_features', base.blocks.basic_blocks.BaseListBlock(wagtail.blocks.StructBlock([('order', wagtail.blocks.ChoiceBlock(choices=[(1, ''), (2, 'a2'), (3, 'a3'), (4, 'a4')], help_text='Select the display order and corresponding style.')), ('icon', base.blocks.basic_blocks.BaseImageBlock(help_text='Select an icon image for the feature.', required=False)), ('text', base.blocks.basic_blocks.BaseCharBlock(help_text='Enter the text for this feature.', required=True))]), help_text='Add up to 4 features to be displayed in the hero section.', label='Features', max_length=4))]))]))], blank=True, help_text='Content for the hero section of the homepage.', null=True),
        ),
    ]
