# Generated by Django 5.0.2 on 2024-03-21 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_homepage_hero_content_homepage_hero_cta_and_more'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_cta',
            field=models.CharField(blank=True, max_length=75, verbose_name='Hero CTA'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_cta_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Hero CTA link'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_heading',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_text',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
