# Generated by Django 5.0.2 on 2024-03-24 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privacypage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='PrivacyIndexPage',
        ),
        migrations.DeleteModel(
            name='PrivacyPage',
        ),
    ]
