# Generated by Django 5.0.2 on 2024-03-22 08:23

import base.blocks.basic
import base.fields.wagtail_fields
import django.db.models.deletion
import wagtail.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcommerceIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', base.fields.wagtail_fields.BaseStreamField([('paragraph', base.blocks.basse.BaseRichTextBlock())], blank=True, null=True)),
                ('categories', base.fields.wagtail_fields.BaseStreamField([('category_link', wagtail.blocks.StructBlock([('name', base.blocks.basse.BaseCharBlock(required=True)), ('url', base.blocks.basse.BaseURLBlock()), ('icon', base.blocks.basse.BaseImageBlock(required=True))]))], blank=True, null=True)),
                ('products', base.fields.wagtail_fields.BaseStreamField([('product', wagtail.blocks.StructBlock([('icon', base.blocks.basse.BaseImageBlock(required=True)), ('title', base.blocks.basse.BaseCharBlock(required=True)), ('description', base.blocks.basse.BaseTextBlock(required=True)), ('price', base.blocks.basse.BaseCharBlock(required=True)), ('compare_at_price', base.blocks.basse.BaseCharBlock(required=False)), ('features', base.blocks.basse.BaseListBlock(wagtail.blocks.StructBlock([('icon', base.blocks.basse.BaseImageBlock(required=True)), ('text', base.blocks.basse.BaseCharBlock(required=True))]))), ('view_plan_url', base.blocks.basse.BaseURLBlock())]))], blank=True, null=True)),
                ('faqs', base.fields.wagtail_fields.BaseStreamField([('faq', wagtail.blocks.StructBlock([('question', base.blocks.basse.BaseCharBlock(required=True)), ('answer', base.blocks.basse.BaseTextBlock(required=True))]))], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
