# Generated by Django 5.0.2 on 2024-04-02 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecommerceindexpage',
            old_name='heading_intro',
            new_name='heading',
        ),
        migrations.RenameField(
            model_name='ecommercepage',
            old_name='heading_intro',
            new_name='heading',
        ),
        migrations.RemoveField(
            model_name='ecommerceindexpage',
            name='heading_title',
        ),
        migrations.RemoveField(
            model_name='ecommercepage',
            name='heading_title',
        ),
        migrations.AddField(
            model_name='ecommerceindexpage',
            name='intro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ecommercepage',
            name='intro',
            field=models.TextField(blank=True, null=True),
        ),
    ]
