# Generated by Django 5.0.2 on 2024-03-24 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecommercepage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='EcommerceIndexPage',
        ),
        migrations.DeleteModel(
            name='EcommercePage',
        ),
    ]
