# Generated by Django 5.0.2 on 2024-06-25 20:04

import django.db.models.deletion
import nfc.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NearFieldCommunicationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('serial_number', models.CharField(db_index=True, max_length=32, unique=True, validators=[nfc.validators.validate_ntag_serial])),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'NTAG',
                'verbose_name_plural': 'NTAGs',
            },
        ),
        migrations.CreateModel(
            name='NearFieldCommunicationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mapping', to='nfc.nearfieldcommunicationtag')),
            ],
        ),
    ]
