# Generated by Django 5.0.2 on 2024-05-27 16:32

import django.db.models.deletion
import nfc.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('digitization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NearFieldCommunicationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('serial_number', models.CharField(db_index=True, max_length=32, unique=True, validators=[nfc.validators.validate_ntag_serial])),
                ('ntag_type', models.CharField(choices=[('NTAG 213', 'NTAG 213'), ('NTAG 215', 'NTAG 215'), ('NTAG 216', 'NTAG 216')], default='NTAG 213', max_length=50)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('digit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ntag', to='digitization.digitalobject')),
            ],
            options={
                'verbose_name': 'NTAG',
                'verbose_name_plural': 'NTAGs',
            },
        ),
    ]
