# Generated by Django 4.2.6 on 2024-01-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='serial_number',
            field=models.CharField(db_index=True, help_text='The unique serial number associated with the NFC tag.', max_length=32, unique=True, verbose_name='Tag Serial Number'),
        ),
    ]
