# Generated by Django 5.0.2 on 2024-05-28 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_itemizeddigitpage_digit_and_more'),
        ('nfc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nearfieldcommunicationtag',
            name='digit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ntag', to='inventory.itemizeddigit'),
        ),
    ]
