# Generated by Django 5.0.2 on 2024-05-31 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_inventorycategorypage_categorypage_and_more'),
        ('nfc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nearfieldcommunicationtag',
            name='digit',
        ),
        migrations.AddField(
            model_name='nearfieldcommunicationtag',
            name='digital_object',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ntag', to='inventory.digitalobject'),
        ),
    ]
