# Generated by Django 5.0.2 on 2024-06-30 14:08

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfc', '0002_nearfieldcommunicationlink_content_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nearfieldcommunicationlink',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='nearfieldcommunicationlink',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='nearfieldcommunicationlink',
            name='tag',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping', to='nfc.nearfieldcommunicationtag'),
        ),
    ]
