# Generated by Django 5.0.2 on 2024-06-20 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfc', '0002_remove_nearfieldcommunicationtag_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NearFieldCommunicationTag',
        ),
    ]
