# Generated by Django 5.0.2 on 2024-06-30 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('nfc', '0003_alter_nearfieldcommunicationlink_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nearfieldcommunicationlink',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='nearfieldcommunicationlink',
            name='object_id',
            field=models.PositiveIntegerField(db_index=True, null=True),
        ),
    ]
