# Generated by Django 5.0.2 on 2024-04-29 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_rename_page_digit_user_remove_digit_ntag'),
        ('nfc', '0003_remove_nearfieldcommunicationtag_counter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nearfieldcommunicationtag',
            name='type',
        ),
        migrations.RemoveField(
            model_name='nearfieldcommunicationtag',
            name='use',
        ),
        migrations.RemoveField(
            model_name='nearfieldcommunicationtag',
            name='user',
        ),
        migrations.AddField(
            model_name='nearfieldcommunicationtag',
            name='digit',
            field=models.ForeignKey(blank=True, help_text='The digital object linked to the NFC tag.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nfc_tags', to='inventory.digit', verbose_name='Digital Object'),
        ),
    ]
