# Generated by Django 5.0.2 on 2024-04-29 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_rename_page_digit_user_remove_digit_ntag'),
        ('nfc', '0004_remove_nearfieldcommunicationtag_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nearfieldcommunicationtag',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='nearfieldcommunicationtag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='nearfieldcommunicationtag',
            name='digit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nfc_tags', to='inventory.digitpage', verbose_name='Digital Object'),
        ),
        migrations.AlterField(
            model_name='nearfieldcommunicationtag',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='nearfieldcommunicationtag',
            name='serial_number',
            field=models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Tag Serial Number'),
        ),
    ]
