# Generated by Django 5.0.2 on 2024-04-29 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfc', '0005_alter_nearfieldcommunicationtag_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nearfieldcommunicationtag',
            old_name='digit',
            new_name='digit_page',
        ),
    ]
