# Generated by Django 5.0.2 on 2024-07-01 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_alter_assetpage_description'),
        ('nfc', '0005_alter_nearfieldcommunicationlink_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nearfieldcommunicationlink',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='nearfieldcommunicationlink',
            name='object_id',
        ),
        migrations.AddField(
            model_name='nearfieldcommunicationlink',
            name='asset',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='asset.assetpage'),
        ),
        migrations.AlterField(
            model_name='nearfieldcommunicationlink',
            name='tag',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nfc_link', to='nfc.nearfieldcommunicationtag'),
        ),
        migrations.AlterField(
            model_name='nearfieldcommunicationtag',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
