# Generated by Django 5.0.2 on 2024-07-01 03:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfc', '0006_remove_nearfieldcommunicationlink_content_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nearfieldcommunicationtag',
            old_name='ntag_type',
            new_name='tag_form',
        ),
        migrations.AddField(
            model_name='nearfieldcommunicationlink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nearfieldcommunicationlink',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
