# Generated by Django 5.0.2 on 2024-04-29 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_digitpage_digit'),
        ('nfc', '0007_remove_nearfieldcommunicationtag_digit_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nearfieldcommunicationtag',
            name='digit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ntag', to='inventory.digit', verbose_name='Digital Object'),
        ),
    ]
