# Generated by Django 5.0.2 on 2024-04-30 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_rename_digittagindexpage_userdigitizedobjecttagindexpage_and_more'),
        ('nfc', '0009_alter_nearfieldcommunicationtag_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nearfieldcommunicationtag',
            name='digit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ntag', to='inventory.userdigitizedobject'),
        ),
    ]
