# Generated by Django 5.0.2 on 2024-07-02 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventory_organism_userprofile_delete_inventorypage'),
        ('nfc', '0009_alter_nearfieldcommunicationtag_serial_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nearfieldcommunicationlink',
            name='asset',
        ),
        migrations.AddField(
            model_name='nearfieldcommunicationlink',
            name='organism',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.organism'),
        ),
    ]
