# Generated by Django 5.0.2 on 2024-05-02 20:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfc', '0010_alter_nearfieldcommunicationtag_digit'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearfieldcommunicationtag',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
