# Generated by Django 5.0.2 on 2024-05-04 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfc', '0011_nearfieldcommunicationtag_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nearfieldcommunicationtag',
            name='digit',
        ),
    ]
