# Generated by Django 5.0.2 on 2024-05-06 21:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfc', '0013_nearfieldcommunicationtag_digitized_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearfieldcommunicationtag',
            name='ntag_type',
            field=models.CharField(choices=[('NTAG 213', 'NTAG 213'), ('NTAG 215', 'NTAG 215'), ('NTAG 216', 'NTAG 216')], default='NTAG 213', max_length=50),
        ),
        migrations.AlterField(
            model_name='nearfieldcommunicationtag',
            name='serial_number',
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
    ]
