# Generated by Django 5.0.2 on 2024-05-06 21:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfc', '0014_nearfieldcommunicationtag_ntag_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nearfieldcommunicationtag',
            name='serial_number',
            field=models.CharField(db_index=True, max_length=32, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_serial_number', message='Serial number must be in the format XX:XX:XX:XX:XX:XX:XX', regex='^([0-9A-Fa-f]{2}:){7}[0-9A-Fa-f]{2}$')]),
        ),
    ]
