# Generated by Django 5.0.2 on 2024-05-10 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_alter_userdigitizedobject_options_and_more'),
        ('nfc', '0018_alter_nearfieldcommunicationtag_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nearfieldcommunicationtag',
            name='digitized_object',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ntag', to='inventory.userdigitizedobject'),
        ),
    ]
