# Generated by Django 5.0.2 on 2024-05-18 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfc', '0019_alter_nearfieldcommunicationtag_digitized_object'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nearfieldcommunicationtag',
            old_name='digitized_object',
            new_name='digit',
        ),
    ]
