# Generated by Django 5.0.2 on 2024-05-19 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitization', '0008_initial'),
        ('nfc', '0020_rename_digitized_object_nearfieldcommunicationtag_digit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nearfieldcommunicationtag',
            name='digit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ntag', to='digitization.userdigit'),
        ),
    ]
