# Generated by Django 5.0.2 on 2024-05-24 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitization', '0009_remove_userdigit_inventory_page_and_more'),
        ('nfc', '0021_alter_nearfieldcommunicationtag_digit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nearfieldcommunicationtag',
            name='digit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ntag', to='digitization.digitalobject'),
        ),
    ]
