# Generated by Django 5.0.2 on 2024-03-22 08:23

import base.blocks.basic
import base.fields.django_fields
import base.fields.wagtail_fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', base.fields.wagtail_fields.BaseStreamField([('paragraph', base.blocks.basse.BaseRichTextBlock())], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CompanyPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', base.fields.django_fields.BaseCharField(blank=True, max_length=255, null=True)),
                ('description', base.fields.wagtail_fields.BaseRichTextField(blank=True)),
                ('body', base.fields.wagtail_fields.BaseStreamField([('paragraph', base.blocks.basse.BaseRichTextBlock()), ('image', base.blocks.basse.BaseImageBlock()), ('url', base.blocks.basse.BaseURLBlock())], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
