# Generated by Django 5.0.2 on 2024-03-31 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyindexpage',
            name='about_mission',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyindexpage',
            name='about_values',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyindexpage',
            name='about_vision',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyindexpage',
            name='lottie_animation_1',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='companyindexpage',
            name='lottie_animation_2',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='companyindexpage',
            name='lottie_animation_2_blur',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='companyindexpage',
            name='quote_heading_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyindexpage',
            name='quote_member_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyindexpage',
            name='quote_member_role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyindexpage',
            name='quote_member_signature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='companyindexpage',
            name='team_heading_subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyindexpage',
            name='team_heading_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyindexpage',
            name='team_member_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='companyindexpage',
            name='team_member_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyindexpage',
            name='team_member_role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
