# Generated by Django 5.0.6 on 2024-07-31 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_teammember_companypage_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypage',
            name='intro',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
