# Generated by Django 5.0.2 on 2024-03-24 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_companyindexpage_introduction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyindexpage',
            name='call_to_action',
        ),
        migrations.RemoveField(
            model_name='companyindexpage',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='companypage',
            name='call_to_action',
        ),
        migrations.RemoveField(
            model_name='companypage',
            name='heading',
        ),
    ]
