# Generated by Django 5.0.2 on 2024-04-01 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companyindexpage_about_mission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyindexpage',
            name='lottie_animation_1',
        ),
        migrations.RemoveField(
            model_name='companyindexpage',
            name='lottie_animation_2',
        ),
        migrations.RemoveField(
            model_name='companyindexpage',
            name='lottie_animation_2_blur',
        ),
        migrations.DeleteModel(
            name='CompanyPage',
        ),
    ]
