# Generated by Django 5.0.2 on 2024-03-24 07:21

import base.blocks.basics
import base.fields.wagtail
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_companyindexpage_call_to_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companypage',
            name='body',
            field=base.fields.wagtail.BaseStreamField([('paragraph', base.blocks.basics.BaseRichTextBlock()), ('image', base.blocks.basics.BaseImageBlock()), ('url', base.blocks.basics.BaseURLBlock())], default=[]),
        ),
    ]
