# Generated by Django 5.0.6 on 2024-08-01 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_teammember_image'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyPage',
            new_name='CompanyIndexPage',
        ),
    ]
