# Generated by Django 5.0.6 on 2024-08-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_rename_companypage_companyindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyindexpage',
            name='our_mission',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companyindexpage',
            name='our_values',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companyindexpage',
            name='our_vision',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companyindexpage',
            name='team_heading',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='companyindexpage',
            name='team_subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
