# Generated by Django 5.0.6 on 2024-08-03 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_companyindexpage_our_mission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMemberRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(choices=[('founder', 'Founder'), ('other', 'Other')], default='other', max_length=20)),
            ],
            options={
                'verbose_name': 'company role',
                'verbose_name_plural': 'company roles',
            },
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name': 'company team member', 'verbose_name_plural': 'company team members'},
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
