# Generated by Django 5.0.6 on 2024-08-03 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_teammemberrole_alter_teammember_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='company.teammemberrole'),
        ),
    ]
