# Generated by Django 5.0.6 on 2024-08-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_team_alter_teammember_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'team', 'verbose_name_plural': 'teams'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name': 'member', 'verbose_name_plural': 'members'},
        ),
        migrations.AlterModelOptions(
            name='teammemberrole',
            options={'verbose_name': 'role', 'verbose_name_plural': 'roles'},
        ),
        migrations.AddField(
            model_name='teammemberrole',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
