# Generated by Django 5.0.6 on 2024-08-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_team_options_alter_teammember_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyindexpage',
            name='team_heading',
        ),
        migrations.RemoveField(
            model_name='companyindexpage',
            name='team_subtitle',
        ),
        migrations.AddField(
            model_name='team',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
