# Generated by Django 5.0.6 on 2024-08-03 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_remove_companyindexpage_team_heading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='heading',
        ),
    ]
