# Generated by Django 5.0.6 on 2024-08-03 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_team_expire_at_team_expired_team_first_published_at_and_more'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='expire_at',
        ),
        migrations.RemoveField(
            model_name='team',
            name='expired',
        ),
        migrations.RemoveField(
            model_name='team',
            name='first_published_at',
        ),
        migrations.RemoveField(
            model_name='team',
            name='go_live_at',
        ),
        migrations.RemoveField(
            model_name='team',
            name='has_unpublished_changes',
        ),
        migrations.RemoveField(
            model_name='team',
            name='last_published_at',
        ),
        migrations.RemoveField(
            model_name='team',
            name='live',
        ),
        migrations.RemoveField(
            model_name='team',
            name='live_revision',
        ),
        migrations.AddField(
            model_name='teammemberrole',
            name='latest_revision',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='latest revision'),
        ),
        migrations.AddField(
            model_name='teammemberrole',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
