# Generated by Django 5.0.6 on 2024-08-03 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_remove_team_expire_at_remove_team_expired_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammemberrole',
            name='sort_order',
        ),
    ]
