# Generated by Django 5.0.2 on 2024-05-02 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitizedobjectregistrationpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='DigitizedObjectRegistrationField',
        ),
        migrations.DeleteModel(
            name='DigitizedObjectRegistrationPage',
        ),
    ]
