# Generated by Django 5.0.2 on 2024-05-27 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('digitization', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalobject',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category'),
        ),
        migrations.AddField(
            model_name='digitalobject',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='digits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='digitalobjectpage',
            name='digit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='page', to='digitization.digitalobject'),
        ),
    ]
