# Generated by Django 5.0.2 on 2024-05-27 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitization', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalobject',
            name='inventory',
        ),
    ]
