# Generated by Django 5.0.2 on 2024-05-28 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitization', '0003_remove_digitalobject_inventory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DigitalObjectPage',
        ),
    ]
