# Generated by Django 5.0.2 on 2024-05-05 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitization', '0003_alter_digitizedobject_description_and_more'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitizedobject',
            name='description',
            field=models.TextField(blank=True, help_text='Provide a detailed description of the object.', null=True),
        ),
        migrations.AlterField(
            model_name='digitizedobject',
            name='name',
            field=models.CharField(help_text='Enter the name of the digitized object.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='digitizedobjectimage',
            name='caption',
            field=models.CharField(blank=True, help_text='Enter a caption for the image.', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='digitizedobjectimage',
            name='image',
            field=models.ForeignKey(help_text='Select an image to associate with the digitized object.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image'),
        ),
    ]
