# Generated by Django 5.0.2 on 2024-05-05 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitization', '0004_alter_digitizedobject_description_and_more'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitizedobject',
            name='description',
            field=models.TextField(blank=True, help_text='Digitized object description.', null=True),
        ),
        migrations.AlterField(
            model_name='digitizedobject',
            name='name',
            field=models.CharField(help_text='Digitized object name.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='digitizedobjectimage',
            name='caption',
            field=models.CharField(blank=True, help_text='Image caption.', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='digitizedobjectimage',
            name='image',
            field=models.ForeignKey(help_text='Digitized object image.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image'),
        ),
    ]
