# Generated by Django 5.0.2 on 2024-05-28 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitization', '0004_delete_digitalobjectpage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalobject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='digits', to=settings.AUTH_USER_MODEL),
        ),
    ]
