# Generated by Django 5.0.2 on 2024-05-31 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitization', '0005_alter_digitalobject_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalobject',
            name='user',
        ),
    ]
