# Generated by Django 5.0.2 on 2024-05-31 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitization', '0006_remove_digitalobject_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalobject',
            name='slug',
            field=models.SlugField(default='slug', editable=False, max_length=255, unique=True, verbose_name='Digitized Object Slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='digitalobject',
            name='description',
            field=models.TextField(blank=True, help_text='Digitized Object Description.', null=True),
        ),
        migrations.AlterField(
            model_name='digitalobject',
            name='name',
            field=models.CharField(help_text='Digitized Object Name.', max_length=100, null=True),
        ),
    ]
