# Generated by Django 5.0.2 on 2024-05-10 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitization', '0006_remove_digitizedobjectimage_digit_and_more'),
        ('inventory', '0024_alter_userdigitizedobject_options_and_more'),
        ('nfc', '0019_alter_nearfieldcommunicationtag_digitized_object'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DigitizedObject',
        ),
        migrations.DeleteModel(
            name='DigitizedObjectImage',
        ),
    ]
