# Generated by Django 5.0.2 on 2024-05-19 03:04

import django.db.models.deletion
import modelcluster.fields
import uuid
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('digitization', '0007_delete_digitizedobject_delete_digitizedobjectimage'),
        ('inventory', '0028_alter_userinventory_unique_together_and_more'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDigitPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='UserDigit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Digitized Object UUID')),
                ('name', models.CharField(help_text='Digitized object name.', max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='Digitized object description.', null=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Digitized Object Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('inventory_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemized_digits', to='inventory.userinventorypage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
