# Generated by Django 5.0.2 on 2024-05-24 01:10

import django.db.models.deletion
import uuid
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('digitization', '0008_initial'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdigit',
            name='inventory_page',
        ),
        migrations.RemoveField(
            model_name='userdigitpage',
            name='page_ptr',
        ),
        migrations.CreateModel(
            name='DigitalObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Digitized Object UUID')),
                ('name', models.CharField(help_text='Digitized object name.', max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='Digitized object description.', null=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Digitized Object Slug')),
                ('object_id', models.PositiveIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='DigitalObjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('digital_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='page', to='digitization.digitalobject')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
