# Generated by Django 5.0.2 on 2024-05-24 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitization', '0009_remove_userdigit_inventory_page_and_more'),
        ('journal', '0002_alter_journalentry_options_remove_journalentry_page_and_more'),
        ('nfc', '0022_alter_nearfieldcommunicationtag_digit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDigit',
        ),
        migrations.DeleteModel(
            name='UserDigitPage',
        ),
    ]
