# Generated by Django 5.0.2 on 2024-05-25 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitization', '0010_delete_userdigit_delete_userdigitpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalobject',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='digitalobject',
            name='object_id',
        ),
    ]
