# Generated by Django 5.0.2 on 2024-05-25 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitization', '0011_remove_digitalobject_content_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='digitalobjectpage',
            old_name='digital_object',
            new_name='digit',
        ),
    ]
