# Generated by Django 5.0.2 on 2024-05-26 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitization', '0012_rename_digital_object_digitalobjectpage_digit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalobject',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='Digitized Object Slug'),
        ),
    ]
