# Generated by Django 5.0.2 on 2024-05-27 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitization', '0013_alter_digitalobject_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalobject',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='digitalobjectpage',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='digitalobjectpage',
            name='intro',
        ),
    ]
