# Generated by Django 5.0.2 on 2024-05-24 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilepage',
            name='profile',
            field=models.OneToOneField(help_text='Link to the associated user profile.', on_delete=django.db.models.deletion.PROTECT, related_name='page', to='profiles.userprofile'),
        ),
    ]
