# Generated by Django 4.2.9 on 2024-02-09 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_author_comment_expert_geography_jurisdiction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geography',
            name='tsn',
            field=models.ForeignKey(db_column='tsn', help_text='Taxonomic Serial Number (TSN) for the Taxonomic Unit.', on_delete=django.db.models.deletion.CASCADE, to='taxonomy.unit', verbose_name='Taxonomic Serial Number'),
        ),
        migrations.AlterField(
            model_name='hierarchy',
            name='tsn',
            field=models.ForeignKey(db_column='tsn', help_text='Taxonomic Serial Number (TSN) for the Taxonomic Unit.', on_delete=django.db.models.deletion.CASCADE, to='taxonomy.unit', verbose_name='Taxonomic Serial Number'),
        ),
        migrations.AlterField(
            model_name='jurisdiction',
            name='tsn',
            field=models.ForeignKey(db_column='tsn', help_text='Taxonomic Serial Number (TSN) for the Taxonomic Unit.', on_delete=django.db.models.deletion.CASCADE, to='taxonomy.unit'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='tsn',
            field=models.IntegerField(db_column='tsn', help_text='The unique identifier for an occurrence of Taxonomic Units.', primary_key=True, serialize=False, verbose_name='Taxonomic Serial Number'),
        ),
        migrations.AlterField(
            model_name='unitcomments',
            name='tsn',
            field=models.ForeignKey(db_column='tsn', help_text='Taxonomic Serial Number (TSN) for the Taxonomic Unit.', on_delete=django.db.models.deletion.CASCADE, to='taxonomy.unit'),
        ),
        migrations.AlterField(
            model_name='unitreferences',
            name='tsn',
            field=models.ForeignKey(db_column='tsn', help_text='Taxonomic Serial Number (TSN) for the Taxonomic Unit.', on_delete=django.db.models.deletion.CASCADE, to='taxonomy.unit'),
        ),
        migrations.AlterField(
            model_name='unitsynonyms',
            name='tsn',
            field=models.ForeignKey(db_column='tsn', help_text='Taxonomic Serial Number (TSN) for the Taxonomic Unit.', on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='taxonomy.unit'),
        ),
        migrations.AlterField(
            model_name='vernacular',
            name='tsn',
            field=models.ForeignKey(db_column='tsn', help_text='Taxonomic Serial Number (TSN) for the Taxonomic Unit.', on_delete=django.db.models.deletion.CASCADE, to='taxonomy.unit'),
        ),
        migrations.AlterField(
            model_name='vernacularreferences',
            name='tsn',
            field=models.ForeignKey(db_column='tsn', help_text='Taxonomic Serial Number (TSN) for the Taxonomic Unit.', on_delete=django.db.models.deletion.CASCADE, to='taxonomy.unit'),
        ),
    ]
