# Generated by Django 4.2.9 on 2024-02-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0003_alter_geography_tsn_alter_hierarchy_tsn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='rank',
            field=models.SmallIntegerField(blank=True, help_text='A unique identifier for a specific level within the taxonomic hierarchy.', null=True, verbose_name='Rank'),
        ),
    ]
