# Generated by Django 4.2.9 on 2024-02-09 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0006_alter_unit_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The taxonomic serial number for the direct parent of the subject occurrence of Taxonomic Units.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='taxonomy.unit', verbose_name='Parent TSN'),
        ),
    ]
