# Generated by Django 4.2.9 on 2024-02-09 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0007_alter_unit_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jurisdiction',
            old_name='jurisdiction_value',
            new_name='jurisdiction',
        ),
        migrations.AlterField(
            model_name='unitsynonyms',
            name='tsn_accepted',
            field=models.ForeignKey(db_column='tsn_accepted', help_text='Taxonomic Serial Number for the accepted Taxonomic Unit.', on_delete=django.db.models.deletion.CASCADE, related_name='accepted_for', to='taxonomy.unit'),
        ),
        migrations.AlterUniqueTogether(
            name='jurisdiction',
            unique_together={('tsn', 'jurisdiction')},
        ),
    ]
