# Generated by Django 4.2.9 on 2024-02-09 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0009_alter_vernacularreferences_vernacular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vernacularreferences',
            name='vernacular',
            field=models.ForeignKey(help_text='Unique identifier for the vernacular name entry.', on_delete=django.db.models.deletion.CASCADE, to='taxonomy.vernacular'),
        ),
    ]
