# Generated by Django 4.2.9 on 2024-02-09 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0010_alter_vernacularreferences_vernacular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='rank',
            field=models.ForeignKey(blank=True, help_text='A unique identifier for a specific level within the taxonomic hierarchy.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.rank', verbose_name='Rank'),
        ),
    ]
