# Generated by Django 4.2.9 on 2024-02-09 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0011_alter_unit_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='direct_parent_rank',
            field=models.ForeignKey(blank=True, help_text='The rank of the direct parent of the current rank.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_children', to='taxonomy.rank', verbose_name='Direct Parent Rank'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='required_parent_rank',
            field=models.ForeignKey(blank=True, help_text='The rank of the required parent of the current rank.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='required_children', to='taxonomy.rank', verbose_name='Required Parent Rank'),
        ),
    ]
