# Generated by Django 4.2.9 on 2024-02-09 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0012_alter_hierarchy_parent_tsn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hierarchy',
            name='parent_tsn',
        ),
    ]
