# Generated by Django 4.2.9 on 2024-02-09 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('taxonomy', '0013_remove_hierarchy_parent_tsn'),
    ]

    operations = [
        migrations.AddField(
            model_name='vernacularreferences',
            name='content_type',
            field=models.ForeignKey(help_text='Expert, Publication, or Other Source model used as a reference.', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='vernacularreferences',
            name='object_id',
            field=models.PositiveIntegerField(help_text='Primary key of the referenced model.', null=True),
        ),
    ]
