# Generated by Django 4.2.9 on 2024-02-09 23:52

from django.db import migrations

def populate_object_id(apps, schema_editor):
    VernacularReferences = apps.get_model('taxonomy', 'VernacularReferences')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    
    # Assuming your models are all in the same app
    prefix_to_model = {
        'EXP': ('taxonomy', 'Expert'),
        'PUB': ('taxonomy', 'Publication'),
        'SRC': ('taxonomy', 'Source'),
    }
    
    for vr in VernacularReferences.objects.all():
        app_label, model_name = prefix_to_model.get(vr.reference_prefix, (None, None))
        if app_label and model_name:
            content_type = ContentType.objects.get(app_label=app_label, model=model_name.lower())
            vr.content_type = content_type
            vr.object_id = vr.reference_id
            vr.save()

class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0014_vernacularreferences_content_type_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_object_id),
    ]
