# Generated by Django 4.2.9 on 2024-02-09 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0014_vernacularreferences_content_type_and_more'),
    ]

    operations = [
    ]
