# Generated by Django 4.2.9 on 2024-02-10 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('taxonomy', '0014_vernacularreferences_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitreferences',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unitreferences',
            name='object_id',
            field=models.PositiveIntegerField(help_text='Primary key of the referenced model.', null=True),
        ),
    ]
