# Generated by Django 4.2.9 on 2024-02-10 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('taxonomy', '0015_unitreferences_content_type_unitreferences_object_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='unitreferences',
            unique_together={('tsn', 'content_type', 'object_id')},
        ),
        migrations.AlterUniqueTogether(
            name='vernacularreferences',
            unique_together={('tsn', 'vernacular', 'content_type', 'object_id')},
        ),
        migrations.RemoveField(
            model_name='unitreferences',
            name='reference_id',
        ),
        migrations.RemoveField(
            model_name='unitreferences',
            name='reference_prefix',
        ),
        migrations.RemoveField(
            model_name='vernacularreferences',
            name='reference_id',
        ),
        migrations.RemoveField(
            model_name='vernacularreferences',
            name='reference_prefix',
        ),
    ]
