# Generated by Django 4.2.9 on 2024-02-10 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0016_alter_unitreferences_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expert',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='publication',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='source',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='expert',
            name='expert_prefix',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='publication_prefix',
        ),
        migrations.RemoveField(
            model_name='source',
            name='source_prefix',
        ),
    ]
