# Generated by Django 4.2.9 on 2024-02-10 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0017_alter_expert_unique_together_and_more'),
    ]

    operations = [
    ]
