# Generated by Django 4.2.9 on 2024-02-10 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0018_auto_20240210_0136'),
    ]

    operations = [
    ]
