# Generated by Django 4.2.9 on 2024-02-10 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0018_auto_20240210_0136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='kingdom',
            old_name='kingdom_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='vernacular',
            old_name='vernacular_id',
            new_name='id',
        ),
    ]
