# Generated by Django 4.2.9 on 2024-02-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0019_auto_20240210_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='temp_g',
            field=models.CharField(default='temp', help_text='The geographic value.', max_length=200, verbose_name='Geographic Value'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='temp_j',
            field=models.CharField(default='temp', help_text='Label signifying a US jurisdictional unit as defined by the TWG, and Canada.', max_length=30),
            preserve_default=False,
        ),
    ]
