# Generated by Django 4.2.9 on 2024-02-10 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0020_unit_temp_g_unit_temp_j'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='temp_g',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='temp_j',
        ),
    ]
