# Generated by Django 4.2.9 on 2024-02-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0022_rename_geography_geography_geography_value_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='unit',
            name='taxonomy_un_complet_7de243_idx',
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['complete_name', 'name_usage'], name='taxonomy_un_complet_c8cb1b_idx'),
        ),
    ]
