# Generated by Django 4.2.9 on 2024-02-11 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0023_remove_unit_taxonomy_un_complet_7de243_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='short_author',
            new_name='cleaned_name',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='author',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='unitsynonyms',
            name='tsn',
            field=models.ForeignKey(db_column='tsn', help_text='Taxonomic Serial Number (TSN) for the Taxonomic Unit.', on_delete=django.db.models.deletion.CASCADE, related_name='accepted_for', to='taxonomy.unit'),
        ),
        migrations.AlterField(
            model_name='unitsynonyms',
            name='tsn_accepted',
            field=models.ForeignKey(db_column='tsn_accepted', help_text='Taxonomic Serial Number for the accepted Taxonomic Unit.', on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='taxonomy.unit'),
        ),
    ]
