# Generated by Django 5.0.2 on 2024-03-23 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solutionspage',
            name='about_sections',
        ),
        migrations.RemoveField(
            model_name='solutionspage',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='solutionspage',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='solutionspage',
            name='team_members',
        ),
        migrations.RemoveField(
            model_name='solutionspage',
            name='top_section',
        ),
    ]
