# Generated by Django 5.0.2 on 2024-03-23 08:42

import base.blocks.basics
import base.fields.wagtail
import django.db.models.deletion
import wagtail.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0002_remove_solutionspage_about_sections_and_more'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('heading', base.fields.wagtail.BaseStreamField([('heading', wagtail.blocks.StructBlock([('title', base.blocks.basics.BaseCharBlock(help_text='Enter the heading title', required=True)), ('text', base.blocks.basics.BaseTextBlock(help_text='Enter the heading text', required=True))]))], null=True)),
                ('call_to_action', base.fields.wagtail.BaseStreamField([('cta', wagtail.blocks.StructBlock([('text', base.blocks.basics.BaseCharBlock()), ('button', wagtail.blocks.StructBlock([('text', base.blocks.basics.BaseCharBlock(help_text='Enter the link title', required=False)), ('url', base.blocks.basics.BaseURLBlock(help_text='Enter the URL', required=False)), ('target', wagtail.blocks.ChoiceBlock(choices=[('_self', 'Same window'), ('_blank', 'New window')], help_text='Where the link should open', required=False))]))]))], null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='solutionindexpage',
            name='introduction',
        ),
        migrations.AddField(
            model_name='solutionindexpage',
            name='call_to_action',
            field=base.fields.wagtail.BaseStreamField([('cta', wagtail.blocks.StructBlock([('text', base.blocks.basics.BaseCharBlock()), ('button', wagtail.blocks.StructBlock([('text', base.blocks.basics.BaseCharBlock(help_text='Enter the link title', required=False)), ('url', base.blocks.basics.BaseURLBlock(help_text='Enter the URL', required=False)), ('target', wagtail.blocks.ChoiceBlock(choices=[('_self', 'Same window'), ('_blank', 'New window')], help_text='Where the link should open', required=False))]))]))], null=True),
        ),
        migrations.AddField(
            model_name='solutionindexpage',
            name='heading',
            field=base.fields.wagtail.BaseStreamField([('heading', wagtail.blocks.StructBlock([('title', base.blocks.basics.BaseCharBlock(help_text='Enter the heading title', required=True)), ('text', base.blocks.basics.BaseTextBlock(help_text='Enter the heading text', required=True))]))], null=True),
        ),
        migrations.DeleteModel(
            name='SolutionsPage',
        ),
    ]
