# Generated by Django 5.0.2 on 2024-03-24 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0003_solutionpage_remove_solutionindexpage_introduction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solutionindexpage',
            name='call_to_action',
        ),
        migrations.RemoveField(
            model_name='solutionindexpage',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='solutionpage',
            name='call_to_action',
        ),
        migrations.RemoveField(
            model_name='solutionpage',
            name='heading',
        ),
    ]
