# Generated by Django 5.0.2 on 2024-03-24 07:21

import base.fields.wagtail
import wagtail.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0004_remove_solutionindexpage_call_to_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionpage',
            name='body',
            field=base.fields.wagtail.BaseStreamField([('heading', wagtail.blocks.StructBlock([])), ('solutions', wagtail.blocks.StructBlock([])), ('problems', wagtail.blocks.StructBlock([])), ('features', wagtail.blocks.StructBlock([])), ('benefits', wagtail.blocks.StructBlock([])), ('cta', wagtail.blocks.StructBlock([]))], default=[]),
        ),
    ]
