# Generated by Django 4.2.6 on 2023-11-24 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kingdoms',
            fields=[
                ('kingdom_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Kingdom ID')),
                ('kingdom_name', models.CharField(max_length=10, verbose_name='Kingdom Name')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
            ],
        ),
        migrations.CreateModel(
            name='UnitTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_id', models.SmallIntegerField(blank=True, null=True, verbose_name='Rank ID')),
                ('rank_name', models.CharField(max_length=15, verbose_name='Rank Name')),
                ('direct_parent_rank_id', models.IntegerField(blank=True, null=True, verbose_name='Direct Parent Rank')),
                ('required_parent_rank_id', models.IntegerField(blank=True, null=True, verbose_name='Required Parent Rank')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('kingdom', models.ForeignKey(blank=True, db_column='kingdom_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='taxonomy.kingdoms', verbose_name='Kingdom')),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('tsn', models.IntegerField(primary_key=True, serialize=False, verbose_name='Taxonomic Serial Number')),
                ('unit_ind1', models.CharField(blank=True, max_length=1, null=True)),
                ('unit_name1', models.CharField(blank=True, max_length=35, null=True)),
                ('unit_ind2', models.CharField(blank=True, max_length=1, null=True)),
                ('unit_name2', models.CharField(blank=True, max_length=35, null=True)),
                ('unit_ind3', models.CharField(blank=True, max_length=7, null=True)),
                ('unit_name3', models.CharField(blank=True, max_length=35, null=True)),
                ('unit_ind4', models.CharField(blank=True, max_length=7, null=True)),
                ('unit_name4', models.CharField(blank=True, max_length=35, null=True)),
                ('unnamed_taxon_ind', models.CharField(blank=True, max_length=7, null=True)),
                ('n_usage', models.CharField(blank=True, max_length=12, null=True)),
                ('unaccept_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('credibility_rtng', models.CharField(blank=True, max_length=40, null=True)),
                ('completeness_rtng', models.CharField(blank=True, max_length=10, null=True)),
                ('currency_rating', models.CharField(blank=True, max_length=7, null=True)),
                ('phylo_sort_seq', models.SmallIntegerField(blank=True, null=True)),
                ('initial_time_stamp', models.DateTimeField(auto_now_add=True)),
                ('taxon_author_id', models.IntegerField(blank=True, null=True)),
                ('hybrid_author_id', models.IntegerField(blank=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('uncertain_prnt_ind', models.CharField(blank=True, max_length=3, null=True)),
                ('name_usage', models.CharField(blank=True, max_length=12, null=True)),
                ('complete_name', models.CharField(blank=True, max_length=300, null=True)),
                ('kingdom', models.ForeignKey(blank=True, db_column='kingdom_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxonomic_units', to='taxonomy.kingdoms')),
                ('parent', models.ForeignKey(blank=True, db_column='parent_tsn', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='taxonomy.units')),
                ('rank', models.ForeignKey(blank=True, db_column='rank_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxonomic_units', to='taxonomy.unittypes')),
            ],
            options={
                'indexes': [models.Index(fields=['complete_name'], name='taxonomy_un_complet_e7fc57_idx')],
            },
        ),
    ]
