# Generated by Django 4.1.7 on 2023-09-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Experts',
        ),
        migrations.DeleteModel(
            name='NODC_IDs',
        ),
        migrations.DeleteModel(
            name='OtherSources',
        ),
        migrations.DeleteModel(
            name='Publications',
        ),
        migrations.DeleteModel(
            name='ReferenceLinks',
        ),
        migrations.DeleteModel(
            name='StrippedAuthor',
        ),
        migrations.DeleteModel(
            name='SynonymLinks',
        ),
        migrations.DeleteModel(
            name='TaxonAuthorsLKUP',
        ),
        migrations.DeleteModel(
            name='TUCommentsLink',
        ),
        migrations.DeleteModel(
            name='VernRefLinks',
        ),
        migrations.AddField(
            model_name='jurisdiction',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jurisdiction',
            name='tsn',
            field=models.IntegerField(verbose_name='Taxonomic Serial Number'),
        ),
        migrations.AlterUniqueTogether(
            name='geographicdivision',
            unique_together={('tsn', 'geographic_value')},
        ),
        migrations.AlterUniqueTogether(
            name='jurisdiction',
            unique_together={('tsn', 'jurisdiction_value')},
        ),
    ]
