# Generated by Django 4.2.6 on 2023-11-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_hierarchy_geographicdivision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='units',
            name='parent',
        ),
        migrations.AddField(
            model_name='units',
            name='parent_tsn',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
