# Generated by Django 4.2.6 on 2023-11-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0003_remove_units_parent_units_parent_tsn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='units',
            name='kingdom',
        ),
        migrations.RemoveField(
            model_name='units',
            name='rank',
        ),
        migrations.AddField(
            model_name='units',
            name='kingdom_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='units',
            name='rank_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
