# Generated by Django 4.2.6 on 2023-11-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0004_remove_units_kingdom_remove_units_rank_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hierarchy',
            options={'verbose_name_plural': 'Hierarchies'},
        ),
        migrations.RemoveField(
            model_name='hierarchy',
            name='geographic_value',
        ),
        migrations.RemoveField(
            model_name='hierarchy',
            name='update_date',
        ),
        migrations.AddField(
            model_name='hierarchy',
            name='children_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Taxonomic Rank'),
        ),
        migrations.AddField(
            model_name='hierarchy',
            name='hierarchy_string',
            field=models.TextField(blank=True, null=True, verbose_name='Hierarchy String'),
        ),
        migrations.AddField(
            model_name='hierarchy',
            name='level',
            field=models.IntegerField(blank=True, null=True, verbose_name='Taxonomic Rank'),
        ),
        migrations.AddField(
            model_name='hierarchy',
            name='parent_tsn',
            field=models.IntegerField(blank=True, db_column='parent_tsn', null=True, verbose_name='Parent Taxonomic Serial Number'),
        ),
    ]
