# Generated by Django 4.2.6 on 2023-11-25 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0005_alter_hierarchy_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kingdoms',
            new_name='Kingdom',
        ),
        migrations.RenameModel(
            old_name='Units',
            new_name='Unit',
        ),
        migrations.RenameModel(
            old_name='UnitTypes',
            new_name='UnitType',
        ),
        migrations.RenameIndex(
            model_name='unit',
            new_name='taxonomy_un_complet_7de243_idx',
            old_name='taxonomy_un_complet_e7fc57_idx',
        ),
    ]
