# Generated by Django 4.2.6 on 2023-11-26 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0006_rename_kingdoms_kingdom_rename_units_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KingdomRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kingdom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='taxonomy.kingdom', verbose_name='Kingdom')),
            ],
            options={
                'verbose_name': 'Kingdom and Rank Combination',
                'verbose_name_plural': 'Kingdom and Rank Combinations',
                'ordering': ['kingdom', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_id', models.SmallIntegerField(verbose_name='Rank ID')),
                ('rank_name', models.CharField(max_length=15, verbose_name='Rank Name')),
                ('direct_parent_rank_id', models.IntegerField(blank=True, null=True, verbose_name='Direct Parent Rank')),
                ('required_parent_rank_id', models.IntegerField(blank=True, null=True, verbose_name='Required Parent Rank')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('kingdom', models.ForeignKey(db_column='kingdom_id', on_delete=django.db.models.deletion.CASCADE, to='taxonomy.kingdom', verbose_name='Kingdom')),
            ],
        ),
        migrations.RemoveField(
            model_name='unit',
            name='kingdom_id',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='parent_tsn',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='rank_id',
        ),
        migrations.AddField(
            model_name='unit',
            name='kingdom',
            field=models.ForeignKey(blank=True, db_column='kingdom_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.kingdom'),
        ),
        migrations.AddField(
            model_name='unit',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent_tsn', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='taxonomy.unit'),
        ),
        migrations.AlterField(
            model_name='hierarchy',
            name='children_count',
            field=models.IntegerField(default=0, verbose_name='Taxonomic Rank'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hierarchy',
            name='hierarchy_string',
            field=models.TextField(default=10, unique=True, verbose_name='Hierarchy String'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hierarchy',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Taxonomic Rank'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hierarchy',
            name='tsn',
            field=models.OneToOneField(db_column='tsn', default=10, on_delete=django.db.models.deletion.CASCADE, related_name='hierarchy', to='taxonomy.unit', verbose_name='Taxonomic Serial Number'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UnitType',
        ),
        migrations.AddField(
            model_name='kingdomrank',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kingdoms', to='taxonomy.rank', verbose_name='Rank'),
        ),
        migrations.AddField(
            model_name='unit',
            name='rank',
            field=models.ForeignKey(blank=True, db_column='rank_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.rank'),
        ),
        migrations.AlterUniqueTogether(
            name='kingdomrank',
            unique_together={('kingdom', 'rank')},
        ),
    ]
