# Generated by Django 4.2.6 on 2023-11-27 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0007_kingdomrank_rank_remove_unit_kingdom_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rank',
            unique_together={('kingdom', 'rank_id')},
        ),
    ]
