# Generated by Django 4.2.6 on 2023-12-03 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0008_alter_rank_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KingdomRank',
        ),
    ]
