# Generated by Django 4.2.6 on 2024-01-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0009_delete_kingdomrank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geographicdivision',
            name='tsn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hierarchy',
            name='tsn',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='unit',
            name='parent',
            field=models.IntegerField(blank=True, db_column='parent_tsn', null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='rank',
            field=models.IntegerField(blank=True, db_column='rank_id', null=True),
        ),
    ]
