# Generated by Django 4.2.6 on 2023-10-30 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0011_taxonunittypes_id_alter_taxonunittypes_kingdom_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hierarchy',
        ),
    ]
