# Generated by Django 4.2.6 on 2023-10-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0013_remove_taxonunittypes_direct_parent_rank_and_more'),
    ]

    operations = [
    ]
