# Generated by Django 4.1.7 on 2023-11-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0014_alter_taxonunittypes_direct_parent_rank_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonunittypes',
            name='direct_parent_rank_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Direct Parent Rank'),
        ),
        migrations.AlterField(
            model_name='taxonunittypes',
            name='required_parent_rank_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Required Parent Rank'),
        ),
    ]
