# Generated by Django 4.2.6 on 2023-11-24 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0016_taxonomicunits_itis_taxono_complet_95ae36_idx'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaxonomicUnits',
            new_name='Units',
        ),
        migrations.RenameModel(
            old_name='TaxonUnitTypes',
            new_name='UnitTypes',
        ),
        migrations.RenameIndex(
            model_name='units',
            new_name='taxonomy_un_complet_e7fc57_idx',
            old_name='taxonomy_taxono_complet_95ae36_idx',
        ),
    ]
